#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:10:00

# Author: Dung Truong and Arnaud Delorme

# make output directory
mkdir -p out_dir

singularity exec -e docker://dtyoung/eegprep python main.py
