"""EEG preprocessing package for MATLAB EEGLAB compatibility."""

from __future__ import annotations

import importlib
import logging
from typing import Any

from .functions.adminfunc.logs import setup_logging

__version__ = "0.2.23"

setup_logging(logging.WARNING)

_LAZY_EXPORTS = {
    "EEG_OPTIONS": ("eegprep.functions.adminfunc.eeg_options", "EEG_OPTIONS"),
    "EEGobj": ("eegprep.functions.eegobj.eegobj", "EEGobj"),
    "ICL_feature_extractor": ("eegprep.plugins.ICLabel.ICL_feature_extractor", "ICL_feature_extractor"),
    "bids_list_eeg_files": ("eegprep.plugins.EEG_BIDS.bids_list_eeg_files", "bids_list_eeg_files"),
    "bids_preproc": ("eegprep.plugins.EEG_BIDS.bids_preproc", "bids_preproc"),
    "cart2topo": ("eegprep.functions.sigprocfunc.cart2topo", "cart2topo"),
    "checkset": ("eegprep.functions.redefine_functions", "checkset"),
    "clean_artifacts": ("eegprep.plugins.clean_rawdata.clean_artifacts", "clean_artifacts"),
    "clean_asr": ("eegprep.plugins.clean_rawdata.clean_asr", "clean_asr"),
    "clean_channels": ("eegprep.plugins.clean_rawdata.clean_channels", "clean_channels"),
    "clean_channels_nolocs": ("eegprep.plugins.clean_rawdata.clean_channels_nolocs", "clean_channels_nolocs"),
    "clean_drifts": ("eegprep.plugins.clean_rawdata.clean_drifts", "clean_drifts"),
    "clean_flatlines": ("eegprep.plugins.clean_rawdata.clean_flatlines", "clean_flatlines"),
    "clean_windows": ("eegprep.plugins.clean_rawdata.clean_windows", "clean_windows"),
    "compare": ("eegprep.functions.redefine_functions", "compare"),
    "coregister": ("eegprep.functions.sigprocfunc.coregister", "coregister"),
    "decodechan": ("eegprep.functions.redefine_functions", "decodechan"),
    "eeg2mne": ("eegprep.functions.redefine_functions", "eeg2mne"),
    "eeg_amica": ("eegprep.functions.popfunc.eeg_amica", "eeg_amica"),
    "eeg_autocorr": ("eegprep.plugins.ICLabel.eeg_autocorr", "eeg_autocorr"),
    "eeg_autocorr_fftw": ("eegprep.plugins.ICLabel.eeg_autocorr_fftw", "eeg_autocorr_fftw"),
    "eeg_autocorr_welch": ("eegprep.plugins.ICLabel.eeg_autocorr_welch", "eeg_autocorr_welch"),
    "eeg_checkset": ("eegprep.functions.adminfunc.eeg_checkset", "eeg_checkset"),
    "eeg_checkset_strict_mode": ("eegprep.functions.adminfunc.eeg_checkset", "strict_mode"),
    "eeg_compare": ("eegprep.functions.popfunc.eeg_compare", "eeg_compare"),
    "eeg_decodechan": ("eegprep.functions.popfunc.eeg_decodechan", "eeg_decodechan"),
    "eeg_eeg2mne": ("eegprep.functions.miscfunc.eeg_eeg2mne", "eeg_eeg2mne"),
    "eeg_eegrej": ("eegprep.functions.popfunc.eeg_eegrej", "eeg_eegrej"),
    "eeg_findboundaries": ("eegprep.functions.popfunc.eeg_findboundaries", "eeg_findboundaries"),
    "eeg_interp": ("eegprep.functions.popfunc.eeg_interp", "eeg_interp"),
    "eeg_lat2point": ("eegprep.functions.popfunc.eeg_lat2point", "eeg_lat2point"),
    "eeg_mne2eeg": ("eegprep.functions.miscfunc.eeg_mne2eeg", "eeg_mne2eeg"),
    "eeg_mne2eeg_epochs": ("eegprep.functions.miscfunc.eeg_mne2eeg_epochs", "eeg_mne2eeg_epochs"),
    "eeg_picard": ("eegprep.functions.popfunc.eeg_picard", "eeg_picard"),
    "eeg_point2lat": ("eegprep.functions.popfunc.eeg_point2lat", "eeg_point2lat"),
    "eeg_rejsuperpose": ("eegprep.functions.popfunc.eeg_rejsuperpose", "eeg_rejsuperpose"),
    "eeg_rpsd": ("eegprep.plugins.ICLabel.eeg_rpsd", "eeg_rpsd"),
    "eeg_runica": ("eegprep.functions.popfunc.eeg_runica", "eeg_runica"),
    "eeglab": ("eegprep.functions.adminfunc.eeglab", "eeglab"),
    "eeglab_clean_artifacts": ("eegprep.functions.adminfunc.eeglabcompat", "clean_artifacts"),
    "eegrej": ("eegprep.functions.sigprocfunc.eegrej", "eegrej"),
    "epoch": ("eegprep.functions.redefine_functions", "epoch"),
    "findboundaries": ("eegprep.functions.redefine_functions", "findboundaries"),
    "gui": ("eegprep.functions.adminfunc.eeglab", "gui"),
    "iclabel": ("eegprep.plugins.ICLabel.iclabel", "iclabel"),
    "eeg_icflag": ("eegprep.plugins.ICLabel.eeg_icflag", "eeg_icflag"),
    "interp": ("eegprep.functions.redefine_functions", "interp"),
    "lat2point": ("eegprep.functions.redefine_functions", "lat2point"),
    "loadset": ("eegprep.functions.popfunc.pop_loadset", "loadset"),
    "mne2eeg": ("eegprep.functions.redefine_functions", "mne2eeg"),
    "mne2eeg_epochs": ("eegprep.functions.redefine_functions", "mne2eeg_epochs"),
    "options": ("eegprep.functions.redefine_functions", "options"),
    "picard": ("eegprep.functions.redefine_functions", "picard"),
    "point2lat": ("eegprep.functions.redefine_functions", "point2lat"),
    "pop_adjustevents": ("eegprep.functions.popfunc.pop_adjustevents", "pop_adjustevents"),
    "pop_autorej": ("eegprep.functions.popfunc.pop_autorej", "pop_autorej"),
    "pop_biosig": ("eegprep.functions.popfunc.pop_biosig", "pop_biosig"),
    "pop_chanevent": ("eegprep.functions.popfunc.pop_chanevent", "pop_chanevent"),
    "pop_chanplot": ("eegprep.functions.studyfunc.pop_chanplot", "pop_chanplot"),
    "pop_chansel": ("eegprep.functions.popfunc.pop_chansel", "pop_chansel"),
    "pop_clean_rawdata": ("eegprep.plugins.clean_rawdata.pop_clean_rawdata", "pop_clean_rawdata"),
    "pop_chanedit": ("eegprep.functions.popfunc.pop_chanedit", "pop_chanedit"),
    "pop_comments": ("eegprep.functions.popfunc.pop_comments", "pop_comments"),
    "pop_copyset": ("eegprep.functions.popfunc.pop_copyset", "pop_copyset"),
    "pop_dipfit_gridsearch": ("eegprep.plugins.dipfit.pop_dipfit_gridsearch", "pop_dipfit_gridsearch"),
    "pop_dipfit_headmodel": ("eegprep.plugins.dipfit.pop_dipfit_headmodel", "pop_dipfit_headmodel"),
    "pop_dipfit_loreta": ("eegprep.plugins.dipfit.pop_dipfit_loreta", "pop_dipfit_loreta"),
    "pop_dipfit_nonlinear": ("eegprep.plugins.dipfit.pop_dipfit_nonlinear", "pop_dipfit_nonlinear"),
    "pop_dipfit_settings": ("eegprep.plugins.dipfit.pop_dipfit_settings", "pop_dipfit_settings"),
    "pop_dipplot": ("eegprep.plugins.dipfit.pop_dipplot", "pop_dipplot"),
    "pop_epoch": ("eegprep.functions.popfunc.pop_epoch", "pop_epoch"),
    "pop_eegfilt": ("eegprep.functions.popfunc.pop_eegfilt", "pop_eegfilt"),
    "pop_eegfiltnew": ("eegprep.plugins.firfilt.pop_eegfiltnew", "pop_eegfiltnew"),
    "pop_eegthresh": ("eegprep.functions.popfunc.pop_eegthresh", "pop_eegthresh"),
    "pop_editset": ("eegprep.functions.popfunc.pop_editset", "pop_editset"),
    "pop_editeventfield": ("eegprep.functions.popfunc.pop_editeventfield", "pop_editeventfield"),
    "pop_editeventvals": ("eegprep.functions.popfunc.pop_editeventvals", "pop_editeventvals"),
    "pop_expevents": ("eegprep.functions.popfunc.pop_expevents", "pop_expevents"),
    "pop_expica": ("eegprep.functions.popfunc.pop_expica", "pop_expica"),
    "pop_export": ("eegprep.functions.popfunc.pop_export", "pop_export"),
    "pop_exportbids": ("eegprep.plugins.EEG_BIDS.pop_exportbids", "pop_exportbids"),
    "pop_fileio": ("eegprep.functions.popfunc.pop_fileio", "pop_fileio"),
    "pop_comperp": ("eegprep.functions.popfunc.pop_comperp", "pop_comperp"),
    "pop_envtopo": ("eegprep.functions.popfunc.pop_envtopo", "pop_envtopo"),
    "pop_erpimage": ("eegprep.functions.popfunc.pop_erpimage", "pop_erpimage"),
    "pop_fileio_brainvision_mat": (
        "eegprep.functions.popfunc.pop_fileio_brainvision_mat",
        "pop_fileio_brainvision_mat",
    ),
    "pop_firma": ("eegprep.plugins.firfilt.pop_firma", "pop_firma"),
    "pop_firpm": ("eegprep.plugins.firfilt.pop_firpm", "pop_firpm"),
    "pop_firws": ("eegprep.plugins.firfilt.pop_firws", "pop_firws"),
    "pop_headplot": ("eegprep.functions.popfunc.pop_headplot", "pop_headplot"),
    "pop_icflag": ("eegprep.plugins.ICLabel.pop_icflag", "pop_icflag"),
    "pop_iclabel": ("eegprep.plugins.ICLabel.pop_iclabel", "pop_iclabel"),
    "pop_jointprob": ("eegprep.functions.popfunc.pop_jointprob", "pop_jointprob"),
    "pop_importbids": ("eegprep.plugins.EEG_BIDS.pop_importbids", "pop_importbids"),
    "pop_importdata": ("eegprep.functions.popfunc.pop_importdata", "pop_importdata"),
    "pop_importepoch": ("eegprep.functions.popfunc.pop_importepoch", "pop_importepoch"),
    "pop_importerplab": ("eegprep.functions.popfunc.pop_importerplab", "pop_importerplab"),
    "pop_importevent": ("eegprep.functions.popfunc.pop_importevent", "pop_importevent"),
    "pop_importpres": ("eegprep.functions.popfunc.pop_importpres", "pop_importpres"),
    "pop_interp": ("eegprep.functions.popfunc.pop_interp", "pop_interp"),
    "pop_load_frombids": ("eegprep.functions.popfunc.pop_load_frombids", "pop_load_frombids"),
    "pop_loadstudy": ("eegprep.functions.studyfunc.pop_loadstudy", "pop_loadstudy"),
    "pop_loadset": ("eegprep.functions.popfunc.pop_loadset", "pop_loadset"),
    "pop_loadset_h5": ("eegprep.functions.popfunc.pop_loadset_h5", "pop_loadset_h5"),
    "pop_leadfield": ("eegprep.plugins.dipfit.pop_leadfield", "pop_leadfield"),
    "pop_mergeset": ("eegprep.functions.popfunc.pop_mergeset", "pop_mergeset"),
    "pop_multifit": ("eegprep.plugins.dipfit.pop_multifit", "pop_multifit"),
    "pop_plotdata": ("eegprep.functions.popfunc.pop_plotdata", "pop_plotdata"),
    "pop_plottopo": ("eegprep.functions.popfunc.pop_plottopo", "pop_plottopo"),
    "pop_prop": ("eegprep.functions.popfunc.pop_prop", "pop_prop"),
    "pop_rejchan": ("eegprep.functions.popfunc.pop_rejchan", "pop_rejchan"),
    "pop_rejcont": ("eegprep.functions.popfunc.pop_rejcont", "pop_rejcont"),
    "pop_rejepoch": ("eegprep.functions.popfunc.pop_rejepoch", "pop_rejepoch"),
    "pop_rejkurt": ("eegprep.functions.popfunc.pop_rejkurt", "pop_rejkurt"),
    "pop_rejmenu": ("eegprep.functions.popfunc.pop_rejmenu", "pop_rejmenu"),
    "pop_rejspec": ("eegprep.functions.popfunc.pop_rejspec", "pop_rejspec"),
    "pop_rejtrend": ("eegprep.functions.popfunc.pop_rejtrend", "pop_rejtrend"),
    "pop_resample": ("eegprep.functions.popfunc.pop_resample", "pop_resample"),
    "pop_reref": ("eegprep.functions.popfunc.pop_reref", "pop_reref"),
    "pop_rmdat": ("eegprep.functions.popfunc.pop_rmdat", "pop_rmdat"),
    "pop_rmbase": ("eegprep.functions.popfunc.pop_rmbase", "pop_rmbase"),
    "pop_runica": ("eegprep.functions.popfunc.pop_runica", "pop_runica"),
    "pop_runscript": ("eegprep.functions.popfunc.pop_runscript", "pop_runscript"),
    "pop_saveh": ("eegprep.functions.popfunc.pop_saveh", "pop_saveh"),
    "pop_savestudy": ("eegprep.functions.studyfunc.pop_savestudy", "pop_savestudy"),
    "pop_saveset": ("eegprep.functions.popfunc.pop_saveset", "pop_saveset"),
    "pop_select": ("eegprep.functions.popfunc.pop_select", "pop_select"),
    "pop_selectevent": ("eegprep.functions.popfunc.pop_selectevent", "pop_selectevent"),
    "pop_selectcomps": ("eegprep.functions.popfunc.pop_selectcomps", "pop_selectcomps"),
    "pop_study": ("eegprep.functions.studyfunc.pop_study", "pop_study"),
    "pop_studyerp": ("eegprep.functions.studyfunc.pop_studyerp", "pop_studyerp"),
    "pop_studywizard": ("eegprep.functions.studyfunc.pop_studywizard", "pop_studywizard"),
    "pop_subcomp": ("eegprep.functions.popfunc.pop_subcomp", "pop_subcomp"),
    "pop_spectopo": ("eegprep.functions.popfunc.pop_spectopo", "pop_spectopo"),
    "pop_timtopo": ("eegprep.functions.popfunc.pop_timtopo", "pop_timtopo"),
    "pop_topoplot": ("eegprep.functions.popfunc.pop_topoplot", "pop_topoplot"),
    "pop_viewprops": ("eegprep.plugins.ICLabel.pop_viewprops", "pop_viewprops"),
    "pop_writeeeg": ("eegprep.functions.popfunc.pop_writeeeg", "pop_writeeeg"),
    "reref": ("eegprep.functions.redefine_functions", "reref"),
    "resample": ("eegprep.functions.redefine_functions", "resample"),
    "rmbase": ("eegprep.functions.sigprocfunc.rmbase", "rmbase"),
    "saveset": ("eegprep.functions.redefine_functions", "saveset"),
    "select": ("eegprep.functions.redefine_functions", "select"),
    "select_multiple_datasets": (
        "eegprep.functions.guifunc.select_multiple_datasets",
        "select_multiple_datasets",
    ),
    "topoplot": ("eegprep.functions.sigprocfunc.topoplot", "topoplot"),
}

__all__ = ["__version__", *_LAZY_EXPORTS]


def __getattr__(name: str) -> Any:
    """Load public EEGPrep exports on first access."""
    try:
        module_name, attr_name = _LAZY_EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    value = getattr(importlib.import_module(module_name), attr_name)
    # Cache the resolved export so normal attribute lookup skips __getattr__.
    globals()[name] = value
    return value
