"""EEG preprocessing package for MATLAB EEGLAB compatibility."""

from __future__ import annotations

import importlib
import logging
from typing import Any

from .functions.adminfunc.logs import setup_logging

__version__ = "0.2.23"

setup_logging(logging.WARNING)

_LAZY_EXPORTS = {
    "CallbackSpec": ("eegprep.functions.guifunc.spec", "CallbackSpec"),
    "ConsoleDatasetResult": ("eegprep.functions.adminfunc.console", "ConsoleDatasetResult"),
    "ConsolePopResult": ("eegprep.functions.adminfunc.console", "ConsolePopResult"),
    "ControlSpec": ("eegprep.functions.guifunc.spec", "ControlSpec"),
    "DialogSpec": ("eegprep.functions.guifunc.spec", "DialogSpec"),
    "EEG_OPTIONS": ("eegprep.functions.adminfunc.eeg_options", "EEG_OPTIONS"),
    "EEGPrepConsoleWorkspace": ("eegprep.functions.adminfunc.console", "EEGPrepConsoleWorkspace"),
    "EEGPrepSession": ("eegprep.functions.guifunc.session", "EEGPrepSession"),
    "EEGobj": ("eegprep.functions.eegobj.eegobj", "EEGobj"),
    "CATALOG_SCHEMA_VERSION": ("eegprep.extension_catalog", "CATALOG_SCHEMA_VERSION"),
    "CatalogValidationIssue": ("eegprep.extension_catalog", "CatalogValidationIssue"),
    "CatalogValidationOptions": ("eegprep.extension_catalog", "CatalogValidationOptions"),
    "CatalogValidationReport": ("eegprep.extension_catalog", "CatalogValidationReport"),
    "EXTENSION_COMPATIBILITY_POLICY": ("eegprep.extensions", "EXTENSION_COMPATIBILITY_POLICY"),
    "EXTENSION_CURATION_POLICY_URL": ("eegprep.extensions", "EXTENSION_CURATION_POLICY_URL"),
    "EXTENSION_NAMING_PREFIX": ("eegprep.extensions", "EXTENSION_NAMING_PREFIX"),
    "EXTENSION_TRUST_MESSAGE": ("eegprep.extensions", "EXTENSION_TRUST_MESSAGE"),
    "CatalogSourceType": ("eegprep.extension_catalog", "CatalogSourceType"),
    "ExtensionAction": ("eegprep.extensions", "ExtensionAction"),
    "ExtensionCatalog": ("eegprep.extension_catalog", "ExtensionCatalog"),
    "ExtensionCatalogEntry": ("eegprep.extension_catalog", "ExtensionCatalogEntry"),
    "ExtensionDependency": ("eegprep.extensions", "ExtensionDependency"),
    "ExtensionLoadError": ("eegprep.extensions", "ExtensionLoadError"),
    "ExtensionMenu": ("eegprep.extensions", "ExtensionMenu"),
    "ExtensionPopFunction": ("eegprep.extensions", "ExtensionPopFunction"),
    "ExtensionRecord": ("eegprep.extensions", "ExtensionRecord"),
    "ExtensionRegistry": ("eegprep.extensions", "ExtensionRegistry"),
    "ExtensionResource": ("eegprep.extensions", "ExtensionResource"),
    "ExtensionSourceType": ("eegprep.extensions", "ExtensionSourceType"),
    "ExtensionSpec": ("eegprep.extensions", "ExtensionSpec"),
    "ExtensionStatus": ("eegprep.extensions", "ExtensionStatus"),
    "ExtensionTestHarness": ("eegprep.extension_testing", "ExtensionTestHarness"),
    "ExtensionValidationResult": ("eegprep.extensions", "ExtensionValidationResult"),
    "ICL_feature_extractor": ("eegprep.plugins.ICLabel.ICL_feature_extractor", "ICL_feature_extractor"),
    "LazyImport": ("eegprep.extensions", "LazyImport"),
    "assert_extension_entry_point_loads": ("eegprep.extension_testing", "assert_extension_entry_point_loads"),
    "bids_list_eeg_files": ("eegprep.plugins.EEG_BIDS.bids_list_eeg_files", "bids_list_eeg_files"),
    "bids_preproc": ("eegprep.plugins.EEG_BIDS.bids_preproc", "bids_preproc"),
    "build_safe_install_commands": ("eegprep.extension_catalog", "build_safe_install_commands"),
    "build_safe_update_commands": ("eegprep.extension_catalog", "build_safe_update_commands"),
    "bundled_plugins": ("eegprep.functions.adminfunc.plugin_menu", "bundled_plugins"),
    "cart2topo": ("eegprep.functions.sigprocfunc.cart2topo", "cart2topo"),
    "check_extension_compatibility": ("eegprep.extensions", "check_extension_compatibility"),
    "checkset": ("eegprep.functions.redefine_functions", "checkset"),
    "clean_artifacts": ("eegprep.plugins.clean_rawdata.clean_artifacts", "clean_artifacts"),
    "clean_asr": ("eegprep.plugins.clean_rawdata.clean_asr", "clean_asr"),
    "clean_channels": ("eegprep.plugins.clean_rawdata.clean_channels", "clean_channels"),
    "clean_channels_nolocs": ("eegprep.plugins.clean_rawdata.clean_channels_nolocs", "clean_channels_nolocs"),
    "clean_drifts": ("eegprep.plugins.clean_rawdata.clean_drifts", "clean_drifts"),
    "clean_flatlines": ("eegprep.plugins.clean_rawdata.clean_flatlines", "clean_flatlines"),
    "clean_windows": ("eegprep.plugins.clean_rawdata.clean_windows", "clean_windows"),
    "compare": ("eegprep.functions.redefine_functions", "compare"),
    "coregister": ("eegprep.functions.sigprocfunc.coregister", "coregister"),
    "decodechan": ("eegprep.functions.redefine_functions", "decodechan"),
    "discover_extensions": ("eegprep.extensions", "discover_extensions"),
    "eeg2mne": ("eegprep.functions.redefine_functions", "eeg2mne"),
    "eeg_amica": ("eegprep.functions.popfunc.eeg_amica", "eeg_amica"),
    "eeg_autocorr": ("eegprep.plugins.ICLabel.eeg_autocorr", "eeg_autocorr"),
    "eeg_autocorr_fftw": ("eegprep.plugins.ICLabel.eeg_autocorr_fftw", "eeg_autocorr_fftw"),
    "eeg_autocorr_welch": ("eegprep.plugins.ICLabel.eeg_autocorr_welch", "eeg_autocorr_welch"),
    "eeg_checkset": ("eegprep.functions.adminfunc.eeg_checkset", "eeg_checkset"),
    "eeg_checkset_strict_mode": ("eegprep.functions.adminfunc.eeg_checkset", "strict_mode"),
    "eeg_compare": ("eegprep.functions.popfunc.eeg_compare", "eeg_compare"),
    "eeg_decodechan": ("eegprep.functions.popfunc.eeg_decodechan", "eeg_decodechan"),
    "eeg_eeg2mne": ("eegprep.functions.miscfunc.eeg_eeg2mne", "eeg_eeg2mne"),
    "eeg_eegrej": ("eegprep.functions.popfunc.eeg_eegrej", "eeg_eegrej"),
    "eeg_emptyset": ("eegprep.functions.popfunc.eeg_emptyset", "eeg_emptyset"),
    "eeg_multieegplot": ("eegprep.functions.popfunc.eeg_multieegplot", "eeg_multieegplot"),
    "eegplot": ("eegprep.functions.sigprocfunc.eegplot", "eegplot"),
    "eeg_findboundaries": ("eegprep.functions.popfunc.eeg_findboundaries", "eeg_findboundaries"),
    "eeg_interp": ("eegprep.functions.popfunc.eeg_interp", "eeg_interp"),
    "eeg_lat2point": ("eegprep.functions.popfunc.eeg_lat2point", "eeg_lat2point"),
    "eeg_mne2eeg": ("eegprep.functions.miscfunc.eeg_mne2eeg", "eeg_mne2eeg"),
    "eeg_mne2eeg_epochs": ("eegprep.functions.miscfunc.eeg_mne2eeg_epochs", "eeg_mne2eeg_epochs"),
    "eeg_picard": ("eegprep.functions.popfunc.eeg_picard", "eeg_picard"),
    "eeg_point2lat": ("eegprep.functions.popfunc.eeg_point2lat", "eeg_point2lat"),
    "eeg_rejsuperpose": ("eegprep.functions.popfunc.eeg_rejsuperpose", "eeg_rejsuperpose"),
    "eeg_retrieve": ("eegprep.functions.adminfunc.eeg_retrieve", "eeg_retrieve"),
    "eeg_rpsd": ("eegprep.plugins.ICLabel.eeg_rpsd", "eeg_rpsd"),
    "eeg_runica": ("eegprep.functions.popfunc.eeg_runica", "eeg_runica"),
    "eeg_store": ("eegprep.functions.adminfunc.eeg_store", "eeg_store"),
    "eeglab": ("eegprep.functions.adminfunc.eeglab", "eeglab"),
    "eeglab_clean_artifacts": ("eegprep.functions.adminfunc.eeglabcompat", "clean_artifacts"),
    "eegrej": ("eegprep.functions.sigprocfunc.eegrej", "eegrej"),
    "epoch": ("eegprep.functions.redefine_functions", "epoch"),
    "extension_version_satisfies": ("eegprep.extensions", "extension_version_satisfies"),
    "findboundaries": ("eegprep.functions.redefine_functions", "findboundaries"),
    "firws": ("eegprep.plugins.firfilt.firws", "firws"),
    "firwsord": ("eegprep.plugins.firfilt.firwsord", "firwsord"),
    "format_plugin_menu": ("eegprep.functions.adminfunc.plugin_menu", "format_plugin_menu"),
    "gui": ("eegprep.functions.adminfunc.eeglab", "gui"),
    "iclabel": ("eegprep.plugins.ICLabel.iclabel", "iclabel"),
    "eeg_icflag": ("eegprep.plugins.ICLabel.eeg_icflag", "eeg_icflag"),
    "inputgui": ("eegprep.functions.guifunc.inputgui", "inputgui"),
    "interp": ("eegprep.functions.redefine_functions", "interp"),
    "lat2point": ("eegprep.functions.redefine_functions", "lat2point"),
    "listdlg2": ("eegprep.functions.guifunc.listdlg2", "listdlg2"),
    "load_catalog_entries": ("eegprep.extension_catalog", "load_catalog_entries"),
    "load_extension_catalog": ("eegprep.extension_catalog", "load_extension_catalog"),
    "loadset": ("eegprep.functions.popfunc.pop_loadset", "loadset"),
    "mne2eeg": ("eegprep.functions.redefine_functions", "mne2eeg"),
    "mne2eeg_epochs": ("eegprep.functions.redefine_functions", "mne2eeg_epochs"),
    "newcrossf": ("eegprep.functions.timefreqfunc.newcrossf", "newcrossf"),
    "newtimef": ("eegprep.functions.timefreqfunc.newtimef", "newtimef"),
    "options": ("eegprep.functions.redefine_functions", "options"),
    "picard": ("eegprep.functions.redefine_functions", "picard"),
    "plugin_menu": ("eegprep.functions.adminfunc.plugin_menu", "plugin_menu"),
    "plugin_status": ("eegprep.functions.adminfunc.plugin_menu", "plugin_status"),
    "point2lat": ("eegprep.functions.redefine_functions", "point2lat"),
    "pop_adjustevents": ("eegprep.functions.popfunc.pop_adjustevents", "pop_adjustevents"),
    "pop_autorej": ("eegprep.functions.popfunc.pop_autorej", "pop_autorej"),
    "pop_biosig": ("eegprep.functions.popfunc.pop_biosig", "pop_biosig"),
    "pop_chanevent": ("eegprep.functions.popfunc.pop_chanevent", "pop_chanevent"),
    "pop_chanplot": ("eegprep.functions.studyfunc.pop_chanplot", "pop_chanplot"),
    "pop_chansel": ("eegprep.functions.popfunc.pop_chansel", "pop_chansel"),
    "pop_clean_rawdata": ("eegprep.plugins.clean_rawdata.pop_clean_rawdata", "pop_clean_rawdata"),
    "pop_chanedit": ("eegprep.functions.popfunc.pop_chanedit", "pop_chanedit"),
    "pop_comments": ("eegprep.functions.popfunc.pop_comments", "pop_comments"),
    "pop_clust": ("eegprep.functions.studyfunc.pop_clust", "pop_clust"),
    "pop_clustedit": ("eegprep.functions.studyfunc.pop_clustedit", "pop_clustedit"),
    "pop_copyset": ("eegprep.functions.popfunc.pop_copyset", "pop_copyset"),
    "pop_delset": ("eegprep.functions.adminfunc.pop_delset", "pop_delset"),
    "pop_dipfit_gridsearch": ("eegprep.plugins.dipfit.pop_dipfit_gridsearch", "pop_dipfit_gridsearch"),
    "pop_dipfit_headmodel": ("eegprep.plugins.dipfit.pop_dipfit_headmodel", "pop_dipfit_headmodel"),
    "pop_dipfit_loreta": ("eegprep.plugins.dipfit.pop_dipfit_loreta", "pop_dipfit_loreta"),
    "pop_dipfit_nonlinear": ("eegprep.plugins.dipfit.pop_dipfit_nonlinear", "pop_dipfit_nonlinear"),
    "pop_dipfit_settings": ("eegprep.plugins.dipfit.pop_dipfit_settings", "pop_dipfit_settings"),
    "pop_dipplot": ("eegprep.plugins.dipfit.pop_dipplot", "pop_dipplot"),
    "pop_epoch": ("eegprep.functions.popfunc.pop_epoch", "pop_epoch"),
    "pop_eegfilt": ("eegprep.functions.popfunc.pop_eegfilt", "pop_eegfilt"),
    "pop_eegfiltnew": ("eegprep.plugins.firfilt.pop_eegfiltnew", "pop_eegfiltnew"),
    "pop_eegthresh": ("eegprep.functions.popfunc.pop_eegthresh", "pop_eegthresh"),
    "pop_editset": ("eegprep.functions.popfunc.pop_editset", "pop_editset"),
    "pop_editoptions": ("eegprep.functions.adminfunc.pop_editoptions", "pop_editoptions"),
    "pop_editeventfield": ("eegprep.functions.popfunc.pop_editeventfield", "pop_editeventfield"),
    "pop_editeventvals": ("eegprep.functions.popfunc.pop_editeventvals", "pop_editeventvals"),
    "pop_eegplot": ("eegprep.functions.popfunc.pop_eegplot", "pop_eegplot"),
    "pop_expevents": ("eegprep.functions.popfunc.pop_expevents", "pop_expevents"),
    "pop_expica": ("eegprep.functions.popfunc.pop_expica", "pop_expica"),
    "pop_export": ("eegprep.functions.popfunc.pop_export", "pop_export"),
    "pop_exportbids": ("eegprep.plugins.EEG_BIDS.pop_exportbids", "pop_exportbids"),
    "pop_fileio": ("eegprep.functions.popfunc.pop_fileio", "pop_fileio"),
    "pop_comperp": ("eegprep.functions.popfunc.pop_comperp", "pop_comperp"),
    "pop_envtopo": ("eegprep.functions.popfunc.pop_envtopo", "pop_envtopo"),
    "pop_erpimage": ("eegprep.functions.popfunc.pop_erpimage", "pop_erpimage"),
    "pop_eventstat": ("eegprep.functions.popfunc.pop_eventstat", "pop_eventstat"),
    "pop_fileio_brainvision_mat": (
        "eegprep.functions.popfunc.pop_fileio_brainvision_mat",
        "pop_fileio_brainvision_mat",
    ),
    "pop_firma": ("eegprep.plugins.firfilt.pop_firma", "pop_firma"),
    "pop_firpm": ("eegprep.plugins.firfilt.pop_firpm", "pop_firpm"),
    "pop_firws": ("eegprep.plugins.firfilt.pop_firws", "pop_firws"),
    "pop_headplot": ("eegprep.functions.popfunc.pop_headplot", "pop_headplot"),
    "pop_icflag": ("eegprep.plugins.ICLabel.pop_icflag", "pop_icflag"),
    "pop_iclabel": ("eegprep.plugins.ICLabel.pop_iclabel", "pop_iclabel"),
    "pop_jointprob": ("eegprep.functions.popfunc.pop_jointprob", "pop_jointprob"),
    "pop_importbids": ("eegprep.plugins.EEG_BIDS.pop_importbids", "pop_importbids"),
    "pop_importdata": ("eegprep.functions.popfunc.pop_importdata", "pop_importdata"),
    "pop_importepoch": ("eegprep.functions.popfunc.pop_importepoch", "pop_importepoch"),
    "pop_importerplab": ("eegprep.functions.popfunc.pop_importerplab", "pop_importerplab"),
    "pop_importevent": ("eegprep.functions.popfunc.pop_importevent", "pop_importevent"),
    "pop_importpres": ("eegprep.functions.popfunc.pop_importpres", "pop_importpres"),
    "pop_interp": ("eegprep.functions.popfunc.pop_interp", "pop_interp"),
    "pop_load_frombids": ("eegprep.functions.popfunc.pop_load_frombids", "pop_load_frombids"),
    "pop_loadstudy": ("eegprep.functions.studyfunc.pop_loadstudy", "pop_loadstudy"),
    "pop_loadset": ("eegprep.functions.popfunc.pop_loadset", "pop_loadset"),
    "pop_loadset_h5": ("eegprep.functions.popfunc.pop_loadset_h5", "pop_loadset_h5"),
    "pop_leadfield": ("eegprep.plugins.dipfit.pop_leadfield", "pop_leadfield"),
    "pop_mergeset": ("eegprep.functions.popfunc.pop_mergeset", "pop_mergeset"),
    "pop_multifit": ("eegprep.plugins.dipfit.pop_multifit", "pop_multifit"),
    "pop_newset": ("eegprep.functions.popfunc.pop_newset", "pop_newset"),
    "pop_newcrossf": ("eegprep.functions.popfunc.pop_newcrossf", "pop_newcrossf"),
    "pop_newtimef": ("eegprep.functions.popfunc.pop_newtimef", "pop_newtimef"),
    "pop_plotdata": ("eegprep.functions.popfunc.pop_plotdata", "pop_plotdata"),
    "pop_plottopo": ("eegprep.functions.popfunc.pop_plottopo", "pop_plottopo"),
    "pop_preclust": ("eegprep.functions.studyfunc.pop_preclust", "pop_preclust"),
    "pop_precomp": ("eegprep.functions.studyfunc.pop_precomp", "pop_precomp"),
    "pop_prop": ("eegprep.functions.popfunc.pop_prop", "pop_prop"),
    "pop_prop_extended": ("eegprep.plugins.ICLabel.pop_prop_extended", "pop_prop_extended"),
    "pop_rejchan": ("eegprep.functions.popfunc.pop_rejchan", "pop_rejchan"),
    "pop_rejcont": ("eegprep.functions.popfunc.pop_rejcont", "pop_rejcont"),
    "pop_rejepoch": ("eegprep.functions.popfunc.pop_rejepoch", "pop_rejepoch"),
    "pop_rejkurt": ("eegprep.functions.popfunc.pop_rejkurt", "pop_rejkurt"),
    "pop_rejmenu": ("eegprep.functions.popfunc.pop_rejmenu", "pop_rejmenu"),
    "pop_rejspec": ("eegprep.functions.popfunc.pop_rejspec", "pop_rejspec"),
    "pop_rejtrend": ("eegprep.functions.popfunc.pop_rejtrend", "pop_rejtrend"),
    "pop_resample": ("eegprep.functions.popfunc.pop_resample", "pop_resample"),
    "pop_reref": ("eegprep.functions.popfunc.pop_reref", "pop_reref"),
    "pop_rmdat": ("eegprep.functions.popfunc.pop_rmdat", "pop_rmdat"),
    "pop_rmbase": ("eegprep.functions.popfunc.pop_rmbase", "pop_rmbase"),
    "pop_runica": ("eegprep.functions.popfunc.pop_runica", "pop_runica"),
    "pop_runscript": ("eegprep.functions.popfunc.pop_runscript", "pop_runscript"),
    "pop_saveh": ("eegprep.functions.popfunc.pop_saveh", "pop_saveh"),
    "pop_savestudy": ("eegprep.functions.studyfunc.pop_savestudy", "pop_savestudy"),
    "pop_saveset": ("eegprep.functions.popfunc.pop_saveset", "pop_saveset"),
    "pop_select": ("eegprep.functions.popfunc.pop_select", "pop_select"),
    "pop_selectevent": ("eegprep.functions.popfunc.pop_selectevent", "pop_selectevent"),
    "pop_selectcomps": ("eegprep.functions.popfunc.pop_selectcomps", "pop_selectcomps"),
    "pop_signalstat": ("eegprep.functions.popfunc.pop_signalstat", "pop_signalstat"),
    "pop_study": ("eegprep.functions.studyfunc.pop_study", "pop_study"),
    "pop_studydesign": ("eegprep.functions.studyfunc.pop_studydesign", "pop_studydesign"),
    "pop_studyerp": ("eegprep.functions.studyfunc.pop_studyerp", "pop_studyerp"),
    "pop_studywizard": ("eegprep.functions.studyfunc.pop_studywizard", "pop_studywizard"),
    "pop_subcomp": ("eegprep.functions.popfunc.pop_subcomp", "pop_subcomp"),
    "pop_spectopo": ("eegprep.functions.popfunc.pop_spectopo", "pop_spectopo"),
    "pop_timtopo": ("eegprep.functions.popfunc.pop_timtopo", "pop_timtopo"),
    "pop_topoplot": ("eegprep.functions.popfunc.pop_topoplot", "pop_topoplot"),
    "pop_viewprops": ("eegprep.plugins.ICLabel.pop_viewprops", "pop_viewprops"),
    "pop_writeeeg": ("eegprep.functions.popfunc.pop_writeeeg", "pop_writeeeg"),
    "pophelp": ("eegprep.functions.guifunc.pophelp", "pophelp"),
    "reref": ("eegprep.functions.redefine_functions", "reref"),
    "resample": ("eegprep.functions.redefine_functions", "resample"),
    "rmbase": ("eegprep.functions.sigprocfunc.rmbase", "rmbase"),
    "saveset": ("eegprep.functions.redefine_functions", "saveset"),
    "select": ("eegprep.functions.redefine_functions", "select"),
    "select_multiple_datasets": (
        "eegprep.functions.guifunc.select_multiple_datasets",
        "select_multiple_datasets",
    ),
    "signalstat": ("eegprep.functions.sigprocfunc.signalstat", "signalstat"),
    "std_checkdatasetinfo": ("eegprep.functions.studyfunc.std_checkset", "std_checkdatasetinfo"),
    "std_checkset": ("eegprep.functions.studyfunc.std_checkset", "std_checkset"),
    "std_clustplot": ("eegprep.functions.studyfunc.std_clustplot", "std_clustplot"),
    "std_createclust": ("eegprep.functions.studyfunc.std_createclust", "std_createclust"),
    "std_editset": ("eegprep.functions.studyfunc.std_editset", "std_editset"),
    "std_erpplot": ("eegprep.functions.studyfunc.std_erpplot", "std_erpplot"),
    "std_erspplot": ("eegprep.functions.studyfunc.std_erspplot", "std_erspplot"),
    "std_itcplot": ("eegprep.functions.studyfunc.std_itcplot", "std_itcplot"),
    "std_makedesign": ("eegprep.functions.studyfunc.std_makedesign", "std_makedesign"),
    "std_mergeclust": ("eegprep.functions.studyfunc.std_mergeclust", "std_mergeclust"),
    "std_movecomp": ("eegprep.functions.studyfunc.std_movecomp", "std_movecomp"),
    "std_moveoutlier": ("eegprep.functions.studyfunc.std_moveoutlier", "std_moveoutlier"),
    "std_preclust": ("eegprep.functions.studyfunc.std_preclust", "std_preclust"),
    "std_precomp": ("eegprep.functions.studyfunc.std_precomp", "std_precomp"),
    "std_readdata": ("eegprep.functions.studyfunc.std_readdata", "std_readdata"),
    "std_readerp": ("eegprep.functions.studyfunc.std_readdata", "std_readerp"),
    "std_readersp": ("eegprep.functions.studyfunc.std_readdata", "std_readersp"),
    "std_readspec": ("eegprep.functions.studyfunc.std_readdata", "std_readspec"),
    "std_rejectoutliers": ("eegprep.functions.studyfunc.std_rejectoutliers", "std_rejectoutliers"),
    "std_renameclust": ("eegprep.functions.studyfunc.std_renameclust", "std_renameclust"),
    "std_selectdesign": ("eegprep.functions.studyfunc.std_selectdesign", "std_selectdesign"),
    "std_specplot": ("eegprep.functions.studyfunc.std_specplot", "std_specplot"),
    "topoplot": ("eegprep.functions.sigprocfunc.topoplot", "topoplot"),
    "validate_extension_spec": ("eegprep.extensions", "validate_extension_spec"),
    "validate_catalog_entries": ("eegprep.extension_catalog", "validate_catalog_entries"),
    "validate_catalog_file": ("eegprep.extension_catalog", "validate_catalog_file"),
}

__all__ = ["__version__", *_LAZY_EXPORTS]


def __getattr__(name: str) -> Any:
    """Load public EEGPrep exports on first access."""
    try:
        module_name, attr_name = _LAZY_EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    value = getattr(importlib.import_module(module_name), attr_name)
    # Cache the resolved export so normal attribute lookup skips __getattr__.
    globals()[name] = value
    return value
