clear
signal.data  = rand(10, 1000);
signal.srate = 100;

max_bad_channels = 0.25;
zthresholds = [-inf 7];
window_len = 1;
window_overlap = 0.66;
max_dropout_fraction = 0.1;
min_clean_fraction = 0.25;
truncate_quant = [0.022 0.6];
step_sizes = [0.01 0.01];
shape_range = 1.7:0.15:3.5;

[signal,sample_mask] = clean_windows_simple(signal, ...
    max_bad_channels, ...
    zthresholds, ...
    window_len, ...
    window_overlap, ...
    max_dropout_fraction, ...
    min_clean_fraction, ...
    truncate_quant, ...
    step_sizes, ...
    shape_range);
