"""EEGLAB-style pop wrapper for channel interpolation."""

from __future__ import annotations

import copy
import logging
import re
from typing import Any

import numpy as np

from eegprep.functions.guifunc.spec import CallbackSpec, ControlSpec, DialogSpec
from eegprep.functions.popfunc.eeg_interp import eeg_interp

logger = logging.getLogger(__name__)

_UNSET = object()


def pop_interp(
    EEG: dict | str | object = _UNSET,
    bad_elec: Any = _UNSET,
    method: str | None = None,
    t_range: Any = None,
    *,
    gui: bool | None = None,
    renderer: Any | None = None,
    alleeg: list[dict] | None = None,
    return_com: bool = False,
):
    """Interpolate EEG channels using EEGLAB ``pop_interp`` semantics.

    Args:
        EEG: EEG dictionary. MATLAB callback-string mode is handled internally
            by the GUI renderer in EEGPrep rather than by public string calls.
        bad_elec: 0-based channel indices, channel labels, or channel-location
            dictionaries to interpolate. When omitted, the EEGLAB-like GUI is
            shown.
        method: Interpolation method. Defaults to ``"spherical"`` when
            ``bad_elec`` is provided, matching EEGLAB.
        t_range: Optional ``[start, end]`` interpolation time range in seconds.
        gui: Force or suppress the GUI path.
        renderer: Optional dialog renderer for tests or alternate frontends.
        alleeg: Optional list of loaded EEG datasets used by the GUI's
            "other dataset" channel-source buttons.
        return_com: Return ``(EEG, command)`` when true.

    Returns:
        dict or tuple: Interpolated EEG, and optionally the EEGLAB history
        command generated by the GUI path.
    """
    if EEG is _UNSET:
        return (None, "") if return_com else None
    if isinstance(EEG, str):
        raise RuntimeError("pop_interp callback-string mode is handled by the EEGPrep GUI renderer")

    if gui is None:
        gui = bad_elec is _UNSET

    com = ""
    if gui:
        gui_result = _run_gui(EEG, renderer=renderer, alleeg=alleeg)
        if gui_result is None:
            return (EEG, com) if return_com else EEG
        bad_elec = gui_result["bad_elec"]
        method = gui_result["method"]
        t_range = gui_result["t_range"]
        com = f"EEG = pop_interp(EEG, {gui_result['chanstr']}, '{method}');"
    elif bad_elec is _UNSET:
        raise ValueError("bad_elec must be provided when gui=False")

    method = "spherical" if method is None else method
    t_range = _normalise_t_range_argument(t_range)
    EEG_in = _remove_interpolated_removed_channels(EEG, bad_elec)
    EEG_out = eeg_interp(EEG_in, bad_elec, method=method, t_range=t_range)
    return (EEG_out, com) if return_com else EEG_out


def pop_interp_dialog_spec(EEG: dict, alleeg: list[dict] | None = None) -> DialogSpec:
    """Return the EEGLAB-like dialog spec for ``pop_interp``."""
    is_continuous = _is_continuous(EEG)
    removedchans = _chanlocs_as_list(EEG.get("chaninfo", {}).get("removedchans", []))
    enabled_removed = bool(removedchans)
    chanlocs = _chanlocs_as_list(EEG.get("chanlocs", []))
    alleeg_chanlocs = _alleeg_chanlocs(alleeg)

    controls: list[ControlSpec] = [
        ControlSpec("text", "What channel(s) do you want to interpolate"),
        ControlSpec("text", "none selected", tag="chanlist"),
        _channel_source_button(
            "Select from removed channels",
            "nondatchan" if is_continuous else "removedchans",
            "pop_interp('nondatchan',gcbf);" if is_continuous else "pop_interp('removedchans',gcbf);",
            enabled_removed,
            removedchans=removedchans,
            chanlocs=chanlocs,
            alleeg=alleeg_chanlocs,
        ),
        _channel_source_button(
            "Select from data channels",
            "datchan",
            "pop_interp('datchan',gcbf);",
            True,
            removedchans=removedchans,
            chanlocs=chanlocs,
            alleeg=alleeg_chanlocs,
        ),
        _channel_source_button(
            "Use specific channels of other dataset",
            "selectchan",
            "pop_interp('selectchan',gcbf);",
            True,
            removedchans=removedchans,
            chanlocs=chanlocs,
            alleeg=alleeg_chanlocs,
        ),
        _channel_source_button(
            "Use all channels from other dataset",
            "uselist",
            "pop_interp('uselist',gcbf);",
            True,
            removedchans=removedchans,
            chanlocs=chanlocs,
            alleeg=alleeg_chanlocs,
        ),
        ControlSpec("spacer"),
        ControlSpec("text", "Interpolation method"),
        ControlSpec(
            "popupmenu",
            "Spherical|Planar (slow)" if is_continuous else "Spherical|spherical(Kang et al.)|Planar (slow)",
            tag="method",
            value=1,
        ),
    ]

    if is_continuous:
        controls.extend(
            [
                ControlSpec("spacer"),
                ControlSpec("text", "Time range [min max] (s)"),
                ControlSpec("edit", tag="timerange", value=""),
                ControlSpec("spacer"),
                ControlSpec("text", "Note: for group level analysis, interpolate in STUDY"),
            ]
        )
        geometry = (1, 1, 1, 1, 1, 1, 1, (1.1, 1), 1, (1.1, 1), 1, 1)
        size = (483, 327)
    else:
        controls.extend(
            [
                ControlSpec("spacer"),
                ControlSpec("text", "Note: for group level analysis, interpolate in STUDY"),
            ]
        )
        geometry = (1, 1, 1, 1, 1, 1, 1, (1.1, 1), 1, 1)
        size = (483, 292)

    return DialogSpec(
        title="Interpolate channel(s) -- pop_interp()",
        controls=tuple(controls),
        geometry=geometry,
        function_name="pop_interp",
        eeglab_source="functions/popfunc/pop_interp.m",
        help_text="pophelp('pop_interp')",
        size=size,
    )


def _channel_source_button(
    label: str,
    source: str,
    matlab_callback: str,
    enabled: bool,
    *,
    removedchans: list[dict[str, Any]],
    chanlocs: list[dict[str, Any]],
    alleeg: tuple[dict[str, Any], ...],
) -> ControlSpec:
    return ControlSpec(
        "pushbutton",
        label,
        callback=CallbackSpec(
            "select_interp_channels",
            params={
                "button": f"interp_{source}",
                "target": "chanlist",
                "source": source,
                "removedchans": tuple(copy.deepcopy(removedchans)),
                "chanlocs": tuple(copy.deepcopy(chanlocs)),
                "alleeg": alleeg,
            },
            matlab_callback=matlab_callback,
        ),
        enabled=enabled,
        tag=f"interp_{source}",
    )


def _run_gui(
    EEG: dict,
    *,
    renderer: Any | None = None,
    alleeg: list[dict] | None = None,
) -> dict[str, Any] | None:
    from eegprep.functions.guifunc.inputgui import inputgui

    logger.warning("interpolation can be done on the fly in studies")
    logger.warning("this function will actually create channels in the dataset")
    logger.warning("do not interpolate channels before running ICA")
    spec = pop_interp_dialog_spec(EEG, alleeg=alleeg)
    result = inputgui(spec, renderer=renderer)
    if not result:
        return None

    selection = result.get("chanlist")
    if not isinstance(selection, dict) or not selection.get("chans"):
        return None

    t_range = _gui_t_range(EEG, result.get("timerange", ""))
    return {
        "bad_elec": selection["chans"],
        "chanstr": selection["chanstr"],
        "method": _gui_method(result.get("method", 1)),
        "t_range": t_range,
    }


def _alleeg_chanlocs(alleeg: list[dict] | None) -> tuple[dict[str, Any], ...]:
    return tuple(
        {"chanlocs": tuple(copy.deepcopy(_chanlocs_as_list(dataset.get("chanlocs", []))))}
        for dataset in (alleeg or [])
    )


def _gui_method(value: Any) -> str:
    if isinstance(value, str):
        text = value.strip().lower()
        if text.isdigit():
            index = int(text)
        elif "kang" in text:
            return "sphericalKang"
        elif "planar" in text:
            return "invdist"
        else:
            return "spherical"
    else:
        index = int(value)
    if index == 1:
        return "spherical"
    if index == 2:
        return "sphericalKang"
    return "invdist"


def _gui_t_range(EEG: dict, value: Any) -> list[float]:
    if not str(value or "").strip():
        # EEGLAB GUI submits the full range explicitly instead of omitting it.
        # Keep this path distinct from command-line default interpolation.
        return [float(EEG.get("xmin", 0)), float(EEG.get("xmax", 0))]
    values = _parse_numeric_text(str(value))
    if len(values) != 2:
        raise ValueError("Time/point range must contain 2 columns exactly")
    if np.floor(max(values)) > float(EEG.get("xmax", 0)):
        raise ValueError("Time/point range exceed upper data limits")
    if min(values) < float(EEG.get("xmin", 0)):
        raise ValueError("Time/point range exceed lower data limits")
    return values


def _normalise_t_range_argument(t_range: Any) -> Any:
    if t_range is None:
        return None
    if isinstance(t_range, str):
        if not t_range.strip():
            return None
        return _parse_numeric_text(t_range)
    if isinstance(t_range, np.ndarray):
        if t_range.size == 0:
            return None
        return t_range.tolist()
    return t_range


def _parse_numeric_text(text: str) -> list[float]:
    cleaned = text.strip().strip("[]")
    if not cleaned:
        return []
    return [float(value) for value in re.split(r"[\s,]+", cleaned) if value]


def _remove_interpolated_removed_channels(EEG: dict, bad_elec: Any) -> dict:
    if not _is_chanloc_sequence(bad_elec):
        return EEG
    removed = _chanlocs_as_list(EEG.get("chaninfo", {}).get("removedchans", []))
    if not removed:
        return EEG

    labels_to_remove = {str(chan.get("labels", "")).lower() for chan in _chanlocs_as_list(bad_elec)}
    EEG_out = copy.deepcopy(EEG)
    chaninfo = copy.deepcopy(EEG_out.get("chaninfo", {}))
    chaninfo["removedchans"] = [
        chan for chan in removed if str(chan.get("labels", "")).lower() not in labels_to_remove
    ]
    EEG_out["chaninfo"] = chaninfo
    return EEG_out


def _is_chanloc_sequence(value: Any) -> bool:
    if isinstance(value, dict):
        return "labels" in value
    if isinstance(value, np.ndarray):
        value = value.tolist()
    return (
        isinstance(value, (list, tuple))
        and bool(value)
        and all(isinstance(item, dict) and "labels" in item for item in value)
    )


def _chanlocs_as_list(value: Any) -> list[dict[str, Any]]:
    if value is None:
        return []
    if isinstance(value, np.ndarray):
        value = value.tolist()
    if isinstance(value, dict):
        return [value]
    return list(value)


def _is_continuous(EEG: dict) -> bool:
    return not EEG.get("epoch")


__all__ = ["pop_interp", "pop_interp_dialog_spec"]
