"""EEGLAB-style statistics helper functions."""

from eegprep.functions.statistics._core import (
    ConcatenatedData,
    FDRResult,
    StatcondResult,
    SurrogateDistribution,
    TwoWayAnovaResult,
    TwoWayEffects,
    anova1_cell,
    anova1rm_cell,
    anova2_cell,
    anova2rm_cell,
    concatdata,
    corrcoef_cell,
    fdr,
    stat_surrogate_ci,
    stat_surrogate_pvals,
    statcond,
    surrogdistrib,
    teststat,
    ttest2_cell,
    ttest_cell,
)

__all__ = [
    "ConcatenatedData",
    "FDRResult",
    "StatcondResult",
    "SurrogateDistribution",
    "TwoWayAnovaResult",
    "TwoWayEffects",
    "anova1_cell",
    "anova1rm_cell",
    "anova2_cell",
    "anova2rm_cell",
    "concatdata",
    "corrcoef_cell",
    "fdr",
    "stat_surrogate_ci",
    "stat_surrogate_pvals",
    "statcond",
    "surrogdistrib",
    "teststat",
    "ttest2_cell",
    "ttest_cell",
]
