"""Capture EEGLAB and EEGPrep UI screenshots for visual parity review."""

from __future__ import annotations

import argparse
import os
import pathlib
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass

try:
    from .config import DEFAULT_MANIFEST, TargetSpec, VisualCase, format_command, load_manifest
except ImportError:  # pragma: no cover - supports direct script execution
    from config import DEFAULT_MANIFEST, TargetSpec, VisualCase, format_command, load_manifest  # ty: ignore[unresolved-import]


DEFAULT_OUTPUT_DIR = pathlib.Path(".visual-parity")
REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
EEGLAB_REFERENCE_ENV = "EEGPREP_EEGLAB_ROOT"


def _eeglab_reference_root() -> pathlib.Path:
    configured = os.environ.get(EEGLAB_REFERENCE_ENV)
    if configured:
        return pathlib.Path(configured).expanduser().resolve()
    if (REPO_ROOT.parent / "eeglab" / "eeglab.m").exists():
        return REPO_ROOT.parent / "eeglab"
    return REPO_ROOT / "src" / "eegprep" / "eeglab"


@dataclass(frozen=True)
class CaptureResult:
    """Result from one target capture command."""

    target: str
    output_path: pathlib.Path
    command: list[str]
    exit_code: int
    stdout: str = ""
    stderr: str = ""

    @property
    def ok(self) -> bool:
        return self.exit_code == 0 and self.output_path.exists()


def _matlab_string(value: pathlib.Path | str) -> str:
    text = str(value).replace("\\", "/").replace("'", "''")
    return f"'{text}'"


def _matlab_run_expression(script_path: pathlib.Path) -> str:
    script = _matlab_string(script_path.as_posix())
    return f"try, run({script}); catch ME, disp(getReport(ME, 'extended')); exit(1); end; exit(0);"


def _split_action(action: str) -> tuple[str, str]:
    base, _separator, variant = action.partition(":")
    return base, variant or "default"


def _main_window_menu_state(menu_label: str, state: str = "") -> str:
    if state:
        return state
    if menu_label == "Study":
        return "study"
    if menu_label:
        return "continuous"
    return ""


def _matlab_capture_helper() -> list[str]:
    return [
        "function write_figure_capture(fig, output_file)",
        "set(fig, 'Units', 'pixels');",
        "drawnow;",
        "pause(0.2);",
        "try",
        "    frame = getframe(fig);",
        "    imwrite(frame.cdata, output_file);",
        "catch getframe_error",
        "    try",
        "        pos = get(fig, 'Position');",
        "        screen_size = java.awt.Toolkit.getDefaultToolkit().getScreenSize();",
        "        x = max(0, round(pos(1)));",
        "        y = max(0, round(screen_size.getHeight() - pos(2) - pos(4)));",
        "        w = max(1, round(pos(3)));",
        "        h = max(1, round(pos(4)));",
        "        robot = java.awt.Robot;",
        "        rect = java.awt.Rectangle(x, y, w, h);",
        "        img = robot.createScreenCapture(rect);",
        "        javax.imageio.ImageIO.write(img, 'png', java.io.File(output_file));",
        "    catch robot_error",
        "        error('Figure capture failed. getframe: %s Robot: %s', getframe_error.message, robot_error.message);",
        "    end",
        "end",
        "end",
        "",
        "function write_figure_screen_capture(fig, output_file)",
        "set(fig, 'Units', 'pixels');",
        "drawnow;",
        "pause(0.2);",
        "try",
        "    pos = get(fig, 'Position');",
        "    screen_size = java.awt.Toolkit.getDefaultToolkit().getScreenSize();",
        "    x = max(0, round(pos(1)));",
        "    y = max(0, round(screen_size.getHeight() - pos(2) - pos(4)));",
        "    w = max(1, round(pos(3)));",
        "    h = max(1, round(pos(4)));",
        "    robot = java.awt.Robot;",
        "    rect = java.awt.Rectangle(x, y, w, h);",
        "    img = robot.createScreenCapture(rect);",
        "    javax.imageio.ImageIO.write(img, 'png', java.io.File(output_file));",
        "catch robot_error",
        "    error('Screen capture failed. Robot: %s', robot_error.message);",
        "end",
        "end",
        "",
        "function open_figure_menu(fig, menu_label)",
        "menu_handle = findobj(fig, 'Type', 'uimenu', 'Label', menu_label);",
        "if isempty(menu_handle)",
        "    error('Could not find menu label: %s', menu_label);",
        "end",
        "drawnow;",
        "pause(0.5);",
        "opened = false;",
        "try",
        "    frames = java.awt.Frame.getFrames();",
        "    for frame_idx = 1:length(frames)",
        "        frame = frames(frame_idx);",
        "        if ~frame.isShowing(), continue; end",
        "        menubar = find_java_menubar(frame);",
        "        if isempty(menubar), continue; end",
        "        for menu_idx = 0:menubar.getMenuCount()-1",
        "            java_menu = menubar.getMenu(menu_idx);",
        "            if isempty(java_menu), continue; end",
        "            if strcmp(char(java_menu.getText()), menu_label)",
        "                java_menu.doClick();",
        "                opened = true;",
        "                pause(0.6);",
        "                return;",
        "            end",
        "        end",
        "    end",
        "catch menu_error",
        "    warning('EEGPrepVisualParity:MenuOpen', 'Java menu open failed: %s', menu_error.message);",
        "end",
        "if ~opened && ismac",
        "    opened = open_macos_menu(menu_label);",
        "    if opened",
        "        pause(0.6);",
        "        return;",
        "    end",
        "end",
        "if ~opened",
        "    warning('EEGPrepVisualParity:MenuOpen', 'Menu was found but could not be opened: %s', menu_label);",
        "end",
        "end",
        "",
        "function menubar = find_java_menubar(component)",
        "menubar = [];",
        "try",
        "    if isa(component, 'javax.swing.JMenuBar')",
        "        menubar = component;",
        "        return;",
        "    end",
        "catch",
        "end",
        "try",
        "    candidate = component.getJMenuBar();",
        "    if ~isempty(candidate)",
        "        menubar = candidate;",
        "        return;",
        "    end",
        "catch",
        "end",
        "try",
        "    children = component.getComponents();",
        "catch",
        "    children = [];",
        "end",
        "for child_idx = 1:length(children)",
        "    menubar = find_java_menubar(children(child_idx));",
        "    if ~isempty(menubar), return; end",
        "end",
        "end",
        "",
        "function opened = open_macos_menu(menu_label)",
        "opened = false;",
        "script_file = [tempname '.applescript'];",
        "safe_label = strrep(menu_label, '\\', '\\\\');",
        "safe_label = strrep(safe_label, '\"', '\\\"');",
        "fid = fopen(script_file, 'w');",
        "if fid == -1, return; end",
        "fprintf(fid, 'set menuLabel to \"%s\"\\n', safe_label);",
        "fprintf(fid, 'tell application \"System Events\"\\n');",
        "fprintf(fid, '  set matlabProcesses to every process whose name contains \"MATLAB\"\\n');",
        "fprintf(fid, '  repeat with matlabProcess in matlabProcesses\\n');",
        "fprintf(fid, '    try\\n');",
        "fprintf(fid, '      tell matlabProcess\\n');",
        "fprintf(fid, '        set frontmost to true\\n');",
        "fprintf(fid, '        delay 0.2\\n');",
        "fprintf(fid, '        click menu bar item menuLabel of menu bar 1\\n');",
        "fprintf(fid, '      end tell\\n');",
        "fprintf(fid, '      return \"opened\"\\n');",
        "fprintf(fid, '    end try\\n');",
        "fprintf(fid, '  end repeat\\n');",
        "fprintf(fid, 'end tell\\n');",
        "fclose(fid);",
        "[status, result] = system(['osascript ' shell_quote(script_file)]);",
        "try, delete(script_file); catch, end",
        "if status == 0",
        "    opened = true;",
        "else",
        "    warning('EEGPrepVisualParity:MenuOpen', 'AppleScript menu open failed: %s', result);",
        "end",
        "end",
        "",
        "function write_macos_screen_capture(output_file)",
        "[status, result] = system(['screencapture -x ' shell_quote(output_file)]);",
        "if status ~= 0",
        "    error('macOS screen capture failed: %s', result);",
        "end",
        "end",
        "",
        "function quoted = shell_quote(value)",
        "quoted = ['''' strrep(value, '''', '''\"''\"''') ''''];",
        "end",
        "",
        "function add_viewprops_menu_if_present(eeglab_root, fig)",
        "if ~isempty(findobj(fig, 'Label', 'View extended channel properties'))",
        "    return;",
        "end",
        "viewprops_root = fullfile(eeglab_root, 'plugins', 'ICLabel', 'viewprops');",
        "if ~exist(fullfile(viewprops_root, 'eegplugin_viewprops.m'), 'file')",
        "    return;",
        "end",
        "addpath(viewprops_root);",
        "try_strings = struct('no_check', '');",
        "catch_strings = struct('add_to_hist', '');",
        "eegplugin_viewprops(fig, try_strings, catch_strings);",
        "drawnow;",
        "end",
        "",
    ]


def _matlab_main_window_demo_helper() -> list[str]:
    return [
        "function make_main_window_state(state)",
        "global EEG ALLEEG CURRENTSET STUDY CURRENTSTUDY;",
        "state = lower(char(state));",
        "if isempty(state) || strcmp(state, 'startup')",
        "    return;",
        "end",
        "ALLEEG = [];",
        "CURRENTSET = 0;",
        "CURRENTSTUDY = 0;",
        "STUDY = [];",
        "if strcmp(state, 'continuous')",
        "    EEG = make_main_window_eeg('continuous', 'menu demo');",
        "    ALLEEG = EEG;",
        "    CURRENTSET = 1;",
        "elseif strcmp(state, 'epoched')",
        "    EEG = make_main_window_eeg('epoched', 'menu epoched');",
        "    ALLEEG = EEG;",
        "    CURRENTSET = 1;",
        "elseif strcmp(state, 'multiple')",
        "    EEG = make_main_window_eeg('continuous', 'menu one');",
        "    ALLEEG = EEG;",
        "    ALLEEG(2) = make_main_window_eeg('continuous', 'menu two');",
        "    CURRENTSET = [1 2];",
        "    EEG = ALLEEG(CURRENTSET);",
        "elseif strcmp(state, 'study')",
        "    EEG = make_main_window_eeg('continuous', 'study demo');",
        "    ALLEEG = EEG;",
        "    CURRENTSET = 1;",
        "    STUDY = make_main_window_study();",
        "    CURRENTSTUDY = 1;",
        "else",
        "    error('Unknown main-window visual state: %s', state);",
        "end",
        "eeglab redraw;",
        "drawnow;",
        "pause(0.5);",
        "end",
        "",
        "function EEG = make_main_window_eeg(kind, setname)",
        "EEG = eeg_emptyset;",
        "EEG.setname = setname;",
        "EEG.filename = [strrep(setname, ' ', '_') '.set'];",
        "EEG.filepath = tempdir;",
        "EEG.nbchan = 4;",
        "EEG.srate = 250;",
        "if strcmp(kind, 'epoched')",
        "    EEG.pnts = 250;",
        "    EEG.trials = 2;",
        "    EEG.xmin = -0.2;",
        "    EEG.xmax = EEG.xmin + (EEG.pnts-1)/EEG.srate;",
        "    EEG.data = zeros(4, EEG.pnts, EEG.trials);",
        "    EEG.epoch = struct('event', {1, 2});",
        "else",
        "    EEG.pnts = 1000;",
        "    EEG.trials = 1;",
        "    EEG.xmin = 0;",
        "    EEG.xmax = (EEG.pnts-1)/EEG.srate;",
        "    EEG.data = zeros(4, EEG.pnts);",
        "    EEG.epoch = [];",
        "end",
        "EEG.chanlocs = struct( ...",
        "    'labels', {'Fp1', 'Fp2', 'Cz', 'Oz'}, ...",
        "    'ref', {'common', 'common', 'common', 'common'}, ...",
        "    'theta', {-18, 18, 0, 180}, ...",
        "    'radius', {0.42, 0.42, 0, 0.42}, ...",
        "    'X', {-0.25, 0.25, 0, 0}, ...",
        "    'Y', {0.75, 0.75, 0, -0.8}, ...",
        "    'Z', {0.55, 0.55, 1, 0.55}, ...",
        "    'type', {'EEG', 'EEG', 'EEG', 'EEG'});",
        "EEG.chaninfo = struct();",
        "EEG.event = struct( ...",
        "    'type', {'stim', 'resp'}, ...",
        "    'latency', {100, 350}, ...",
        "    'duration', {0, 0});",
        "EEG.urevent = [];",
        "EEG.history = '';",
        "EEG.saved = 'yes';",
        "EEG.icaweights = eye(4);",
        "EEG.icasphere = eye(4);",
        "EEG.icawinv = eye(4);",
        "EEG.icachansind = 1:4;",
        "if strcmp(kind, 'epoched')",
        "    EEG.icaact = zeros(4, EEG.pnts, EEG.trials);",
        "else",
        "    EEG.icaact = zeros(4, EEG.pnts);",
        "end",
        "end",
        "",
        "function STUDY = make_main_window_study()",
        "STUDY = struct();",
        "STUDY.name = 'menu study';",
        "STUDY.filepath = tempdir;",
        "STUDY.filename = 'menu_study.study';",
        "STUDY.task = 'demo task';",
        "STUDY.subject = {'S01'};",
        "STUDY.condition = {'C1'};",
        "STUDY.session = {};",
        "STUDY.group = {};",
        "STUDY.datasetinfo = struct('index', 1, 'subject', 'S01', 'condition', 'C1', 'session', [], 'group', '');",
        "STUDY.cluster = struct('name', 'ParentCluster');",
        "STUDY.etc = struct();",
        "STUDY.saved = 'yes';",
        "end",
        "",
    ]


def _command_values(case: VisualCase, target_name: str, output_path: pathlib.Path) -> dict[str, str]:
    width, height = case.window_size
    return {
        "case_id": case.id,
        "target": target_name,
        "output": output_path.as_posix(),
        "output_dir": output_path.parent.as_posix(),
        "width": str(width),
        "height": str(height),
        "repo_root": REPO_ROOT.as_posix(),
        "python": sys.executable,
    }


def _output_path(output_dir: pathlib.Path, case_id: str, target_name: str) -> pathlib.Path:
    base_dir = output_dir if output_dir.is_absolute() else REPO_ROOT / output_dir
    return (base_dir / case_id / f"{target_name}.png").resolve()


def _target_env(case: VisualCase, target_name: str, target: TargetSpec, output_path: pathlib.Path) -> dict[str, str]:
    width, height = case.window_size
    env = os.environ.copy()
    src_path = (REPO_ROOT / "src").as_posix()
    env["PYTHONPATH"] = src_path + (os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else "")
    env.update(
        {
            "EEGPREP_VISUAL_CASE_ID": case.id,
            "EEGPREP_VISUAL_TARGET": target_name,
            "EEGPREP_VISUAL_ACTION": target.action,
            "EEGPREP_VISUAL_OUTPUT": output_path.as_posix(),
            "EEGPREP_VISUAL_OUTPUT_DIR": output_path.parent.as_posix(),
            "EEGPREP_VISUAL_WINDOW_WIDTH": str(width),
            "EEGPREP_VISUAL_WINDOW_HEIGHT": str(height),
            "EEGPREP_REPO_ROOT": REPO_ROOT.as_posix(),
        }
    )
    env.update(target.env)
    return env


def _write_matlab_figure_script(case: VisualCase, target: TargetSpec, output_path: pathlib.Path) -> pathlib.Path:
    width, height = case.window_size
    eeglab_root = _eeglab_reference_root()
    script_path = output_path.parent / f"{case.id}_eeglab_capture.m"
    matlab_command = target.matlab_command.strip() or "eeglab;"
    action, variant = _split_action(target.action)
    menu_label = variant if action == "open_menu" else ""
    main_window_state = variant if action == "main_window_state" else ""
    main_window_state = _main_window_menu_state(menu_label, main_window_state)
    script_path.write_text(
        "\n".join(
            [
                "eegprep_visual_capture();",
                "",
                "function eegprep_visual_capture()",
                "try",
                f"output_file = {_matlab_string(output_path)};",
                f"menu_label = {_matlab_string(menu_label)};",
                f"main_window_state = {_matlab_string(main_window_state)};",
                f"eeglab_root = {_matlab_string(eeglab_root)};",
                "addpath(eeglab_root);",
                "set(0, 'DefaultFigureVisible', 'on');",
                matlab_command,
                "initial_fig = findobj('tag', 'EEGLAB');",
                "if ~isempty(initial_fig)",
                "    add_viewprops_menu_if_present(eeglab_root, initial_fig(1));",
                "end",
                "if ~isempty(main_window_state)",
                "    make_main_window_state(main_window_state);",
                "end",
                "drawnow;",
                "pause(1);",
                "fig = findobj('tag', 'EEGLAB');",
                "if isempty(fig)",
                "    fig = gcf;",
                "else",
                "    fig = fig(1);",
                "end",
                "add_viewprops_menu_if_present(eeglab_root, fig);",
                f"set(fig, 'Units', 'pixels', 'Position', [100 100 {width} {height}]);",
                "drawnow;",
                "pause(0.5);",
                "if ~isempty(menu_label)",
                "    open_figure_menu(fig, menu_label);",
                "    write_figure_screen_capture(fig, output_file);",
                "else",
                "    write_figure_capture(fig, output_file);",
                "end",
                "exit(0);",
                "catch ME",
                "disp(getReport(ME, 'extended'));",
                "exit(1);",
                "end",
                "end",
                *_matlab_capture_helper(),
                *_matlab_main_window_demo_helper(),
                "eegprep_visual_capture();",
                "",
            ]
        )
    )
    return script_path


def _write_matlab_reref_dialog_script(
    case: VisualCase,
    output_path: pathlib.Path,
    variant: str = "default",
) -> pathlib.Path:
    eeglab_root = _eeglab_reference_root()
    script_path = output_path.parent / f"{case.id}_eeglab_capture.m"
    script_path.write_text(
        "\n".join(
            [
                "eegprep_visual_capture();",
                "",
                "function eegprep_visual_capture()",
                "capture_timer = [];",
                "try",
                f"output_file = {_matlab_string(output_path)};",
                f"capture_variant = {_matlab_string(variant)};",
                f"eeglab_root = {_matlab_string(eeglab_root)};",
                "addpath(genpath(eeglab_root));",
                "set(0, 'DefaultFigureVisible', 'on');",
                "EEG = eeg_emptyset;",
                "EEG.setname = 'reref demo';",
                "EEG.nbchan = 4;",
                "EEG.pnts = 1000;",
                "EEG.trials = 1;",
                "EEG.srate = 250;",
                "EEG.xmin = 0;",
                "EEG.xmax = (EEG.pnts-1)/EEG.srate;",
                "EEG.data = zeros(4, EEG.pnts);",
                "EEG.chanlocs = struct( ...",
                "    'labels', {'Fp1', 'Fp2', 'Cz', 'Oz'}, ...",
                "    'ref', {'common', 'common', 'common', 'common'}, ...",
                "    'theta', {-18, 18, 0, 180}, ...",
                "    'radius', {0.42, 0.42, 0, 0.42}, ...",
                "    'X', {-0.25, 0.25, 0, 0}, ...",
                "    'Y', {0.75, 0.75, 0, -0.8}, ...",
                "    'Z', {0.55, 0.55, 1, 0.55}, ...",
                "    'type', {'EEG', 'EEG', 'EEG', 'EEG'});",
                "EEG.chaninfo = struct();",
                "EEG.chaninfo.nodatchans = struct('labels', {'M1'}, 'theta', {-90}, 'radius', {0.5}, 'type', {'REF'});",
                "EEG.chaninfo.removedchans = struct( ...",
                "    'labels', {'Pz'}, ...",
                "    'theta', {180}, ...",
                "    'radius', {0.25}, ...",
                "    'X', {0}, ...",
                "    'Y', {-0.4}, ...",
                "    'Z', {0.8}, ...",
                "    'type', {'EEG'});",
                "EEG.ref = 'common';",
                "EEG.icaweights = [];",
                "EEG.icasphere = [];",
                "EEG.icawinv = [];",
                "EEG.icaact = [];",
                "EEG.icachansind = [];",
                "capture_timer = timer( ...",
                "    'ExecutionMode', 'fixedSpacing', ...",
                "    'Period', 0.5, ...",
                "    'StartDelay', 0.5, ...",
                "    'UserData', struct('output_file', output_file, 'variant', capture_variant), ...",
                "    'TimerFcn', @capture_pop_reref_dialog);",
                "start(capture_timer);",
                "[EEG, com] = pop_reref(EEG);",
                "if exist(output_file, 'file') ~= 2",
                "    error('visual parity capture did not create %s', output_file);",
                "end",
                "try, stop(capture_timer); delete(capture_timer); catch, end",
                "exit(0);",
                "catch ME",
                "try, if ~isempty(capture_timer), stop(capture_timer); delete(capture_timer); end, catch, end",
                "disp(getReport(ME, 'extended'));",
                "exit(1);",
                "end",
                "end",
                "",
                "function capture_pop_reref_dialog(timer_obj, ~)",
                "payload = get(timer_obj, 'UserData');",
                "output_file = payload.output_file;",
                "variant = payload.variant;",
                "fig = findall(0, 'Type', 'figure', 'Name', 'pop_reref - average reference or re-reference data');",
                "if isempty(fig)",
                "    figs = findall(0, 'Type', 'figure');",
                "    for idx = 1:length(figs)",
                "        fig_name = get(figs(idx), 'Name');",
                "        if contains(fig_name, 'pop_reref') || contains(fig_name, 'reference')",
                "            fig = figs(idx);",
                "            break;",
                "        end",
                "    end",
                "end",
                "if isempty(fig)",
                "    figs = findall(0, 'Type', 'figure');",
                "    for idx = 1:length(figs)",
                "        if ~isempty(findobj('parent', figs(idx), 'tag', 'ok'))",
                "            fig = figs(idx);",
                "            break;",
                "        end",
                "    end",
                "end",
                "if isempty(fig), return; end",
                "fig = fig(1);",
                "ok_button = findobj('parent', fig, 'tag', 'ok');",
                "if isempty(ok_button), return; end",
                "set(fig, 'Units', 'pixels');",
                "apply_pop_reref_variant(fig, variant);",
                "drawnow;",
                "pause(0.2);",
                "write_figure_capture(fig, output_file);",
                "set(ok_button, 'userdata', 'retuninginputui');",
                "stop(timer_obj);",
                "delete(timer_obj);",
                "end",
                "",
                "function apply_pop_reref_variant(fig, variant)",
                "if strcmpi(variant, 'channels')",
                "    set(findobj('parent', fig, 'tag', 'ave'), 'Value', 0);",
                "    set(findobj('parent', fig, 'tag', 'huberef'), 'Value', 0);",
                "    set(findobj('parent', fig, 'tag', 'rerefstr'), 'Value', 1);",
                "    set(findobj('parent', fig, 'tag', 'reref'), 'Enable', 'on', 'String', 'Fp1');",
                "    set(findobj('parent', fig, 'tag', 'refbr'), 'Enable', 'on');",
                "    set(findobj('parent', fig, 'tag', 'keepref'), 'Enable', 'on', 'Value', 1);",
                "elseif strcmpi(variant, 'huber')",
                "    set(findobj('parent', fig, 'tag', 'ave'), 'Value', 0);",
                "    set(findobj('parent', fig, 'tag', 'rerefstr'), 'Value', 0);",
                "    set(findobj('parent', fig, 'tag', 'huberef'), 'Value', 1);",
                "    set(findobj('parent', fig, 'tag', 'reref'), 'Enable', 'off');",
                "    set(findobj('parent', fig, 'tag', 'refbr'), 'Enable', 'off');",
                "    set(findobj('parent', fig, 'tag', 'keepref'), 'Enable', 'off', 'Value', 0);",
                "elseif strcmpi(variant, 'interp_removed')",
                "    set(findobj('parent', fig, 'tag', 'interp'), 'Value', 1);",
                "end",
                "end",
                "",
                *_matlab_capture_helper(),
                "",
            ]
        )
    )
    return script_path


def _write_matlab_simple_pop_dialog_script(
    case: VisualCase,
    output_path: pathlib.Path,
    action: str,
    variant: str = "default",
) -> pathlib.Path:
    eeglab_root = _eeglab_reference_root()
    script_path = output_path.parent / f"{case.id}_eeglab_capture.m"
    inputgui_override_dir = output_path.parent / "inputgui_plot_override"
    plugin_override_dir = output_path.parent / "dipfit_plugin_override"
    inputgui_override_dir.mkdir(exist_ok=True)
    plugin_override_dir.mkdir(exist_ok=True)
    (inputgui_override_dir / "inputgui.m").write_text(
        "\n".join(
            [
                "function varargout = inputgui(varargin)",
                "override_dir = fileparts(mfilename('fullpath'));",
                "rmpath(override_dir);",
                "cleanup = onCleanup(@() addpath(override_dir, '-begin'));",
                "args = force_plot_mode(varargin);",
                "[varargout{1:nargout}] = inputgui(args{:});",
                "end",
                "",
                "function args = force_plot_mode(args)",
                "if isempty(args), return; end",
                "if ischar(args{1}) || isstring(args{1})",
                "    mode_index = [];",
                "    title_index = [];",
                "    for idx = 1:2:length(args)-1",
                "        if ischar(args{idx}) || isstring(args{idx})",
                "            if strcmpi(char(args{idx}), 'mode')",
                "                mode_index = idx + 1;",
                "            elseif strcmpi(char(args{idx}), 'title')",
                "                title_index = idx + 1;",
                "            end",
                "        end",
                "    end",
                "    visual_title = getenv('EEGPREP_VISUAL_DIALOG_TITLE');",
                "    if isempty(visual_title), visual_title = 'inputgui'; end",
                "    if isempty(title_index)",
                "        args = [args {'title' visual_title}];",
                "    elseif isempty(args{title_index})",
                "        args{title_index} = visual_title;",
                "    end",
                "    if isempty(mode_index)",
                "        args = [args {'mode' 'plot'}];",
                "    else",
                "        args{mode_index} = 'plot';",
                "    end",
                "    return;",
                "end",
                "while length(args) < 6",
                "    args{end+1} = [];",
                "end",
                "if isempty(args{4})",
                "    visual_title = getenv('EEGPREP_VISUAL_DIALOG_TITLE');",
                "    if isempty(visual_title), visual_title = 'inputgui'; end",
                "    args{4} = visual_title;",
                "end",
                "args{6} = 'plot';",
                "end",
                "",
            ]
        )
    )
    (plugin_override_dir / "plugin_askinstall.m").write_text(
        "\n".join(
            [
                "function status = plugin_askinstall(varargin)",
                "% Visual parity capture runs without installing optional EEGLAB plugins.",
                "status = true;",
                "end",
                "",
            ]
        )
    )
    title_by_action = {
        "pop_adjustevents": "Adjust event latencies - pop_adjustevents()",
        "pop_interp": "Interpolate channel(s) -- pop_interp()",
        "pop_select": "Select data -- pop_select()",
        "pop_resample": "Resample current dataset -- pop_resample()",
        "pop_epoch": "Extract data epochs - pop_epoch()",
        "pop_rmbase": "Baseline removal - pop_rmbase()",
        "pop_eegfilt": "Filter the data -- pop_eegfilt()",
        "pop_eegfiltnew": "Filter the data -- pop_eegfiltnew()",
        "pop_firws": "Filter the data -- pop_firws()",
        "pop_firpm": "Filter the data -- pop_firpm()",
        "pop_firma": "Filter the data -- pop_firma()",
        "pop_topoplot": "Plot ERP scalp maps in 2-D -- pop_topoplot()",
        "pop_spectopo": "Channel spectra and maps -- pop_spectopo()",
        "pop_prop": "Channel properties - pop_prop()",
        "pop_timtopo": "Channel ERPs with scalp maps -- pop_timtopo()",
        "pop_plottopo": "Topographic ERP plot - pop_plottopo()",
        "pop_headplot": "ERP head plot(s) -- pop_headplot()",
        "coregister": "coregister()",
        "pop_plotdata": "Component ERPs in rect. array -- pop_plotdata()",
        "pop_erpimage": "Channel ERP image -- pop_erpimage()",
        "pop_envtopo": "Plot component and ERP envelopes -- pop_envtopo()",
        "pop_comperp": "ERP grand average/RMS - pop_comperp()",
        "pop_newtimef": "Plot channel time frequency -- pop_newtimef()",
        "pop_newcrossf": "Plot channel cross-coherence -- pop_newcrossf()",
        "pop_signalstat": "Plot signal statistics -- pop_signalstat()",
        "pop_eventstat": "Plot event statistics -- pop_eventstat()",
        "pop_runica": "Run ICA decomposition -- pop_runica()",
        "pop_subcomp": "Remove components from data -- pop_subcomp()",
        "pop_autorej": "Automatic epoch rejection -- pop_autorej()",
        "pop_eegthresh": "Rejection abnormal elec. values -- pop_eegthresh()",
        "pop_jointprob": "Data probability rejection -- pop_jointprob()",
        "pop_rejchan": "Reject channel -- pop_rejchan()",
        "pop_rejcont": "Reject continuous portions of data - pop_rejcont()",
        "pop_rejkurt": "Data kurtosis rejection -- pop_rejkurt()",
        "pop_rejmenu": "Reject trials using data statistics - pop_rejmenu()",
        "pop_rejspec": "Reject by data spectra -- pop_rejspec()",
        "pop_rejtrend": "Data trend rejection -- pop_rejtrend()",
        "pop_selectcomps": "Reject components by map -- pop_selectcomps()",
        "pop_viewprops": "View many chan or comp. properties -- pop_viewprops",
        "pop_clean_rawdata": "pop_clean_rawdata()",
        "pop_comments": "Read/Enter text -- pop_comments()",
        "pop_editset": "Edit dataset information - pop_editset()",
        "pop_editeventfield": "Edit event field(s) -- pop_editeventfield()",
        "pop_editeventvals": "Edit event values -- pop_editeventvals()",
        "pop_selectevent": "Select events -- pop_selectevent()",
        "pop_rmdat": "Remove data portions around events - pop_rmdat()",
        "pop_chanedit": "Edit channel info -- pop_chanedit()",
        "pop_copyset": "Copy dataset -- pop_copyset()",
        "pop_mergeset": "Merge datasets -- pop_mergeset()",
        "pop_study": "Create a new STUDY set -- pop_study()",
        "pop_studydesign": "Edit STUDY design -- pop_studydesign()",
        "pop_iclabel": "ICLabel",
        "pop_icflag": "Flag components using ICLabel -- pop_icflag()",
        "pop_dipfit_settings": "Dipole fit settings - pop_dipfit_settings()",
        "pop_dipfit_headmodel": "Create headmodel from MRI - pop_dipfit_headmodel",
        "pop_dipfit_gridsearch": "Batch dipole fit -- pop_dipfit_gridsearch()",
        "pop_dipfit_nonlinear": "Manual dipole fit -- pop_dipfit_nonlinear()",
        "pop_dipplot": "Plot dipoles - pop_dipplot",
        "pop_multifit": "Fit multiple ICA components -- pop_multifit()",
        "pop_leadfield": "Compute ROI activity",
        "pop_dipfit_loreta": "Localization of ICA components using eLoreta -- pop_dipfit_loreta()",
    }
    if action == "pop_topoplot" and variant == "components":
        target_title = "Plot component scalp maps in 2-D -- pop_topoplot()"
    elif action == "pop_spectopo" and variant == "components":
        target_title = "Component spectra and maps -- pop_spectopo()"
    elif action == "pop_prop" and variant == "components":
        target_title = "Component properties - pop_prop()"
    elif action == "pop_headplot" and variant == "components":
        target_title = "Component head plot(s) -- pop_headplot()"
    elif action == "pop_erpimage" and variant == "components":
        target_title = "Component ERP image -- pop_erpimage()"
    elif action == "pop_newtimef" and variant == "components":
        target_title = "Plot component time frequency -- pop_newtimef()"
    elif action == "pop_newcrossf" and variant == "components":
        target_title = "Plot component cross-coherence -- pop_newcrossf()"
    else:
        target_title = title_by_action[action]
    script_path.write_text(
        "\n".join(
            [
                "eegprep_visual_capture();",
                "",
                "function eegprep_visual_capture()",
                "try",
                f"output_file = {_matlab_string(output_path)};",
                f"target_title = {_matlab_string(target_title)};",
                f"action = {_matlab_string(action)};",
                f"variant = {_matlab_string(variant)};",
                f"eeglab_root = {_matlab_string(eeglab_root)};",
                f"headplot_resource_root = {_matlab_string(REPO_ROOT / 'src' / 'eegprep' / 'resources' / 'headplot')};",
                f"inputgui_override_dir = {_matlab_string(inputgui_override_dir)};",
                f"plugin_override_dir = {_matlab_string(plugin_override_dir)};",
                "addpath(genpath(eeglab_root));",
                "addpath(plugin_override_dir, '-begin');",
                "addpath(inputgui_override_dir, '-begin');",
                "if strcmp(action, 'coregister')",
                "    setenv('EEGPREP_VISUAL_OUTPUT_FILE', output_file);",
                "    patch_coregister_for_capture(eeglab_root);",
                "end",
                "set(0, 'DefaultFigureVisible', 'on');",
                "setenv('EEGPREP_VISUAL_DIALOG_TITLE', target_title);",
                "EEG = make_simple_pop_demo(action, variant);",
                "if strcmp(action, 'pop_runica') && strcmp(variant, 'multiple')",
                "    EEG(2) = make_simple_pop_demo(action, variant);",
                "    EEG(2).setname = 'pop demo two';",
                "end",
                "switch action",
                "    case 'pop_adjustevents'",
                "        [EEG, com] = pop_adjustevents(EEG);",
                "    case 'pop_study'",
                "        ALLEEG = EEG;",
                "        ALLEEG.setname = 'study targets';",
                "        ALLEEG.filename = 'study_targets.set';",
                "        ALLEEG.filepath = '/tmp';",
                "        ALLEEG.subject = 'S01';",
                "        ALLEEG.condition = 'target';",
                "        ALLEEG.group = 'control';",
                "        ALLEEG.session = 1;",
                "        ALLEEG.run = 1;",
                "        ALLEEG(2) = EEG;",
                "        ALLEEG(2).setname = 'study standards';",
                "        ALLEEG(2).filename = 'study_standards.set';",
                "        ALLEEG(2).filepath = '/tmp';",
                "        ALLEEG(2).subject = 'S02';",
                "        ALLEEG(2).condition = 'standard';",
                "        ALLEEG(2).group = 'control';",
                "        ALLEEG(2).session = 1;",
                "        ALLEEG(2).run = 1;",
                "        [STUDY, ALLEEG, com] = pop_study([], ALLEEG, 'gui', 'on');",
                "    case 'pop_studydesign'",
                "        ALLEEG = EEG;",
                "        ALLEEG.setname = 'study targets';",
                "        ALLEEG.filename = 'study_targets.set';",
                "        ALLEEG.filepath = '/tmp';",
                "        ALLEEG.subject = 'S01';",
                "        ALLEEG.condition = 'target';",
                "        ALLEEG.group = 'control';",
                "        ALLEEG.session = 1;",
                "        ALLEEG.run = 1;",
                "        ALLEEG(2) = EEG;",
                "        ALLEEG(2).setname = 'study standards';",
                "        ALLEEG(2).filename = 'study_standards.set';",
                "        ALLEEG(2).filepath = '/tmp';",
                "        ALLEEG(2).subject = 'S02';",
                "        ALLEEG(2).condition = 'standard';",
                "        ALLEEG(2).group = 'control';",
                "        ALLEEG(2).session = 1;",
                "        ALLEEG(2).run = 1;",
                "        [STUDY, ALLEEG] = std_editset([], ALLEEG, 'name', 'menu study');",
                "        [STUDY, ALLEEG] = std_checkset(STUDY, ALLEEG);",
                "        [STUDY, com] = pop_studydesign(STUDY, ALLEEG);",
                "    case 'pop_interp'",
                "        [EEG, com] = pop_interp(EEG);",
                "    case 'pop_select'",
                "        [EEG, com] = pop_select(EEG);",
                "    case 'pop_resample'",
                "        [EEG, com] = pop_resample(EEG);",
                "    case 'pop_epoch'",
                "        [EEG, com] = pop_epoch(EEG);",
                "    case 'pop_rmbase'",
                "        [EEG, com] = pop_rmbase(EEG);",
                "    case 'pop_eegfilt'",
                "        [EEG, com] = pop_eegfilt(EEG);",
                "    case 'pop_eegfiltnew'",
                "        [EEG, com] = pop_eegfiltnew(EEG);",
                "    case 'pop_firws'",
                "        [EEG, com] = pop_firws(EEG);",
                "    case 'pop_firpm'",
                "        [EEG, com] = pop_firpm(EEG);",
                "    case 'pop_firma'",
                "        [EEG, com] = pop_firma(EEG);",
                "    case 'pop_topoplot'",
                "        if strcmp(variant, 'components')",
                "            com = pop_topoplot(EEG, 0);",
                "        else",
                "            com = pop_topoplot(EEG, 1);",
                "        end",
                "    case 'pop_spectopo'",
                "        if strcmp(variant, 'components')",
                "            com = pop_spectopo(EEG, 0);",
                "        else",
                "            com = pop_spectopo(EEG, 1);",
                "        end",
                "    case 'pop_prop'",
                "        if strcmp(variant, 'components')",
                "            com = pop_prop(EEG, 0);",
                "        else",
                "            com = pop_prop(EEG, 1);",
                "        end",
                "    case 'pop_timtopo'",
                "        com = pop_timtopo(EEG);",
                "    case 'pop_plottopo'",
                "        com = pop_plottopo(EEG);",
                "    case 'pop_headplot'",
                "        warning_timer = timer('ExecutionMode', 'fixedSpacing', 'Period', 0.5, 'StartDelay', 0.5, 'TimerFcn', @(~, ~) close_headplot_warning());",
                "        capture_timer = timer('ExecutionMode', 'fixedSpacing', 'Period', 0.5, 'StartDelay', 1.0, 'TimerFcn', @(~, ~) capture_simple_pop_dialog(output_file, target_title, action));",
                "        start(warning_timer); start(capture_timer);",
                "        if strcmp(variant, 'components')",
                "            com = pop_headplot(EEG, 0);",
                "        else",
                "            com = pop_headplot(EEG, 1);",
                "        end",
                "        try, stop(capture_timer); delete(capture_timer); catch, end",
                "        try, stop(warning_timer); delete(warning_timer); catch, end",
                "    case 'coregister'",
                "        mesh_file = fullfile(headplot_resource_root, 'mheadnew.mat');",
                "        mesh_chan_file = fullfile(headplot_resource_root, 'mheadnew.xyz');",
                "        [~, transform] = coregister(EEG.chanlocs, mesh_chan_file, 'mesh', mesh_file, 'chaninfo1', EEG.chaninfo, 'transform', [0 -10 0 -0.1 0 -1.6 1100 1100 1100], 'title', 'Co-registration plot for headplot mesh');",
                "    case 'pop_plotdata'",
                "        com = pop_plotdata(EEG);",
                "    case 'pop_erpimage'",
                "        if strcmp(variant, 'components')",
                "            com = pop_erpimage(EEG, 0);",
                "        else",
                "            com = pop_erpimage(EEG, 1);",
                "        end",
                "    case 'pop_envtopo'",
                "        com = pop_envtopo(EEG);",
                "    case 'pop_comperp'",
                "        ALLEEG = EEG;",
                "        ALLEEG(2) = EEG;",
                "        ALLEEG(2).setname = 'pop demo two';",
                "        if strcmp(variant, 'components')",
                "            pop_comperp(ALLEEG, 0);",
                "        else",
                "            pop_comperp(ALLEEG, 1);",
                "        end",
                "    case 'pop_newtimef'",
                "        if strcmp(variant, 'components')",
                "            com = pop_newtimef(EEG, 0);",
                "        else",
                "            com = pop_newtimef(EEG, 1);",
                "        end",
                "    case 'pop_newcrossf'",
                "        if strcmp(variant, 'components')",
                "            com = pop_newcrossf(EEG, 0);",
                "        else",
                "            com = pop_newcrossf(EEG, 1);",
                "        end",
                "    case 'pop_signalstat'",
                "        if strcmp(variant, 'components')",
                "            com = pop_signalstat(EEG, 0);",
                "        else",
                "            com = pop_signalstat(EEG, 1);",
                "        end",
                "    case 'pop_eventstat'",
                "        com = pop_eventstat(EEG);",
                "    case 'pop_runica'",
                "        [EEG, com] = pop_runica(EEG);",
                "    case 'pop_subcomp'",
                "        [EEG, com] = pop_subcomp(EEG);",
                "    case 'pop_autorej'",
                "        [EEG, com] = pop_autorej(EEG);",
                "    case 'pop_eegthresh'",
                "        [EEG, com] = pop_eegthresh(EEG, 1);",
                "    case 'pop_jointprob'",
                "        [EEG, com] = pop_jointprob(EEG, 1);",
                "    case 'pop_rejchan'",
                "        [EEG, com] = pop_rejchan(EEG);",
                "    case 'pop_rejcont'",
                "        [EEG, com] = pop_rejcont(EEG);",
                "    case 'pop_rejkurt'",
                "        [EEG, com] = pop_rejkurt(EEG, 1);",
                "    case 'pop_rejmenu'",
                "        pop_rejmenu(EEG, 1); com = '';",
                "    case 'pop_rejspec'",
                "        [EEG, com] = pop_rejspec(EEG, 1);",
                "    case 'pop_rejtrend'",
                "        [EEG, com] = pop_rejtrend(EEG, 1);",
                "    case 'pop_selectcomps'",
                "        [EEG, com] = pop_selectcomps(EEG);",
                "    case 'pop_viewprops'",
                "        com = pop_viewprops(EEG, 0);",
                "    case 'pop_clean_rawdata'",
                "        [EEG, com] = pop_clean_rawdata(EEG);",
                "    case 'pop_comments'",
                "        capture_timer = timer('ExecutionMode', 'fixedSpacing', 'Period', 0.5, 'StartDelay', 1.0, 'TimerFcn', @(~, ~) capture_simple_pop_dialog(output_file, target_title, action));",
                "        start(capture_timer);",
                "        [EEG, com] = pop_comments(EEG, 'About this dataset');",
                "        try, stop(capture_timer); delete(capture_timer); catch, end",
                "    case 'pop_editset'",
                "        [EEG, com] = pop_editset(EEG);",
                "    case 'pop_editeventfield'",
                "        [EEG, com] = pop_editeventfield(EEG);",
                "    case 'pop_editeventvals'",
                "        capture_timer = timer('ExecutionMode', 'fixedSpacing', 'Period', 0.5, 'StartDelay', 1.0, 'TimerFcn', @(~, ~) capture_simple_pop_dialog(output_file, target_title, action));",
                "        start(capture_timer);",
                "        [EEG, com] = pop_editeventvals(EEG);",
                "        try, stop(capture_timer); delete(capture_timer); catch, end",
                "    case 'pop_selectevent'",
                "        [EEG, com] = pop_selectevent(EEG);",
                "    case 'pop_rmdat'",
                "        [EEG, com] = pop_rmdat(EEG);",
                "    case 'pop_chanedit'",
                "        capture_timer = timer('ExecutionMode', 'fixedSpacing', 'Period', 0.5, 'StartDelay', 1.0, 'TimerFcn', @(~, ~) capture_simple_pop_dialog(output_file, target_title, action));",
                "        start(capture_timer);",
                "        [EEG, com] = pop_chanedit(EEG);",
                "        try, stop(capture_timer); delete(capture_timer); catch, end",
                "    case 'pop_copyset'",
                "        ALLEEG = EEG;",
                "        [ALLEEG, EEG, CURRENTSET, com] = pop_copyset(ALLEEG, 1);",
                "    case 'pop_mergeset'",
                "        ALLEEG = EEG;",
                "        ALLEEG(2) = EEG;",
                "        ALLEEG(2).setname = 'pop demo two';",
                "        [EEG, com] = pop_mergeset(ALLEEG);",
                "    case 'pop_iclabel'",
                "        [EEG, com] = pop_iclabel(EEG);",
                "    case 'pop_icflag'",
                "        [EEG, com] = pop_icflag(EEG);",
                "    case 'pop_dipfit_settings'",
                "        [EEG, com] = pop_dipfit_settings(EEG);",
                "    case 'pop_dipfit_headmodel'",
                "        [EEG, com] = pop_dipfit_headmodel(EEG, fullfile(eeglab_root, 'sample_data', 'eeglab_data.set'));",
                "    case 'pop_dipfit_gridsearch'",
                "        EEG = pop_dipfit_settings(EEG, 'model', 'standardBEM');",
                "        [EEG, com] = pop_dipfit_gridsearch(EEG);",
                "    case 'pop_dipfit_nonlinear'",
                "        capture_dipfit_nonlinear_reference(output_file); com = '';",
                "    case 'pop_dipplot'",
                "        EEG = pop_dipfit_settings(EEG, 'model', 'standardBEM');",
                "        EEG.dipfit.model(1).posxyz = [0 -20 40]; EEG.dipfit.model(1).momxyz = [1 0 0]; EEG.dipfit.model(1).rv = 0.12;",
                "        com = pop_dipplot(EEG);",
                "    case 'pop_multifit'",
                "        EEG = pop_dipfit_settings(EEG, 'model', 'standardBEM');",
                "        [EEG, com] = pop_multifit(EEG);",
                "    case 'pop_leadfield'",
                "        EEG = pop_dipfit_settings(EEG, 'model', 'standardBEM');",
                "        [EEG, com] = pop_leadfield(EEG);",
                "    case 'pop_dipfit_loreta'",
                "        EEG = pop_dipfit_settings(EEG, 'model', 'standardBEM');",
                "        EEG.dipfit.sourcemodel = struct('pos', [0 0 0], 'leadfield', []);",
                "        com = pop_dipfit_loreta(EEG);",
                "end",
                "if exist(output_file, 'file') ~= 2",
                "    capture_simple_pop_dialog(output_file, target_title, action);",
                "end",
                "if exist(output_file, 'file') ~= 2",
                "    error('visual parity capture did not create %s', output_file);",
                "end",
                "exit(0);",
                "catch ME",
                "disp(getReport(ME, 'extended'));",
                "exit(1);",
                "end",
                "end",
                "",
                "function EEG = make_simple_pop_demo(action, variant)",
                "EEG = eeg_emptyset;",
                "EEG.setname = 'pop demo';",
                "EEG.subject = 'S01';",
                "EEG.condition = 'targets';",
                "EEG.group = 'control';",
                "EEG.run = 1;",
                "EEG.session = 1;",
                "EEG.ref = 'common';",
                "EEG.nbchan = 4;",
                "EEG.pnts = 1000;",
                "EEG.trials = 1;",
                "EEG.srate = 250;",
                "EEG.xmin = 0;",
                "EEG.xmax = (EEG.pnts-1)/EEG.srate;",
                "EEG.data = zeros(4, EEG.pnts);",
                "EEG.chanlocs = struct( ...",
                "    'labels', {'Fp1', 'Fp2', 'Cz', 'Oz'}, ...",
                "    'ref', {'common', 'common', 'common', 'common'}, ...",
                "    'theta', {-18, 18, 0, 180}, ...",
                "    'radius', {0.42, 0.42, 0, 0.42}, ...",
                "    'X', {-0.25, 0.25, 0, 0}, ...",
                "    'Y', {0.75, 0.75, 0, -0.8}, ...",
                "    'Z', {0.55, 0.55, 1, 0.55}, ...",
                "    'type', {'EEG', 'EEG', 'EEG', 'EEG'});",
                "EEG.chaninfo = struct();",
                "EEG.event = struct('type', {'stim', 'resp'}, 'latency', {100, 350}, 'duration', {0, 0});",
                "EEG.urevent = EEG.event;",
                "EEG.history = '';",
                "EEG.saved = 'yes';",
                "EEG.comments = 'Existing sample dataset comments.';",
                "EEG.icaweights = eye(4);",
                "EEG.icasphere = eye(4);",
                "EEG.icawinv = eye(4);",
                "EEG.icachansind = 1:4;",
                "EEG.icaact = zeros(4, EEG.pnts);",
                "EEG.reject.gcompreject = zeros(1, 4);",
                "EEG.etc.ic_classification.ICLabel.classifications = [ ...",
                "    0.70 0.10 0.10 0.03 0.02 0.03 0.02; ...",
                "    0.02 0.94 0.02 0.01 0.00 0.00 0.01; ...",
                "    0.05 0.02 0.91 0.01 0.00 0.00 0.01; ...",
                "    0.80 0.05 0.05 0.02 0.02 0.03 0.03];",
                "EEG.etc.ic_classification.ICLabel.classes = { ...",
                "    'Brain', 'Muscle', 'Eye', 'Heart', 'Line Noise', 'Channel Noise', 'Other' };",
                "if strcmp(action, 'pop_adjustevents')",
                "    EEG.nbchan = 1;",
                "    EEG.data = zeros(1, EEG.pnts);",
                "    EEG.chanlocs = struct('labels', {'Cz'}, 'type', {'EEG'});",
                "    EEG.icaweights = [];",
                "    EEG.icasphere = [];",
                "    EEG.icawinv = [];",
                "    EEG.icachansind = [];",
                "    EEG.icaact = [];",
                "end",
                "if strcmp(action, 'pop_interp') && strcmp(variant, 'removed')",
                "    EEG.chaninfo.removedchans = struct( ...",
                "        'labels', {'M1', 'M2'}, ...",
                "        'theta', {-90, 90}, ...",
                "        'radius', {0.5, 0.5}, ...",
                "        'X', {-0.8, 0.8}, ...",
                "        'Y', {0, 0}, ...",
                "        'Z', {0.4, 0.4}, ...",
                "        'type', {'EEG', 'EEG'});",
                "end",
                "if strcmp(action, 'pop_interp') && strcmp(variant, 'epoched')",
                "    EEG.pnts = 500;",
                "    EEG.trials = 2;",
                "    EEG.data = zeros(4, EEG.pnts, EEG.trials);",
                "    EEG.xmax = (EEG.pnts-1)/EEG.srate;",
                "    EEG.epoch = struct('event', {1, 2});",
                "    EEG.icaact = zeros(4, EEG.pnts, EEG.trials);",
                "end",
                "if strcmp(action, 'pop_rmbase')",
                "    EEG.pnts = 500;",
                "    EEG.trials = 2;",
                "    EEG.xmin = -0.2;",
                "    EEG.xmax = 0.796;",
                "    EEG.times = linspace(-200, 796, EEG.pnts);",
                "    EEG.data = zeros(4, EEG.pnts, EEG.trials);",
                "    EEG.epoch = struct('event', {1, 2});",
                "    EEG.icaact = zeros(4, EEG.pnts, EEG.trials);",
                "end",
                "if any(strcmp(action, {'pop_autorej', 'pop_eegthresh', 'pop_jointprob', 'pop_rejkurt', 'pop_rejmenu', 'pop_rejspec', 'pop_rejtrend'})) || ismember(action, {'pop_timtopo', 'pop_plottopo', 'pop_plotdata', 'pop_erpimage', 'pop_envtopo', 'pop_comperp', 'pop_newtimef', 'pop_newcrossf', 'pop_signalstat', 'pop_eventstat'})",
                "    EEG.pnts = 250;",
                "    EEG.trials = 2;",
                "    EEG.xmin = -0.2;",
                "    EEG.xmax = 0.796;",
                "    EEG.times = linspace(-200, 796, EEG.pnts);",
                "    EEG.data = zeros(4, EEG.pnts, EEG.trials);",
                "    EEG.epoch = struct('event', {1, 2});",
                "    EEG.icaact = zeros(4, EEG.pnts, EEG.trials);",
                "end",
                "if any(strcmp(action, {'pop_autorej', 'pop_eegthresh', 'pop_jointprob', 'pop_rejkurt', 'pop_rejmenu', 'pop_rejspec', 'pop_rejtrend'}))",
                "    EEG.reject.rejthresh = [0 1];",
                "    EEG.reject.rejthreshE = false(4, 2);",
                "    EEG.reject.rejmanual = [0 0];",
                "    EEG.reject.rejmanualE = false(4, 2);",
                "    EEG.reject.rejconst = [0 0];",
                "    EEG.reject.rejconstE = false(4, 2);",
                "    EEG.reject.rejjp = [0 0];",
                "    EEG.reject.rejjpE = false(4, 2);",
                "    EEG.reject.rejkurt = [0 0];",
                "    EEG.reject.rejkurtE = false(4, 2);",
                "    EEG.reject.rejfreq = [0 0];",
                "    EEG.reject.rejfreqE = false(4, 2);",
                "    EEG.reject.icarejmanual = [0 0];",
                "    EEG.reject.icarejmanualE = false(4, 2);",
                "    EEG.reject.icarejthresh = [0 0];",
                "    EEG.reject.icarejthreshE = false(4, 2);",
                "    EEG.reject.icarejconst = [0 0];",
                "    EEG.reject.icarejconstE = false(4, 2);",
                "    EEG.reject.icarejjp = [0 0];",
                "    EEG.reject.icarejjpE = false(4, 2);",
                "    EEG.reject.icarejkurt = [0 0];",
                "    EEG.reject.icarejkurtE = false(4, 2);",
                "    EEG.reject.icarejfreq = [0 0];",
                "    EEG.reject.icarejfreqE = false(4, 2);",
                "    EEG.reject.rejmanualcol = [1 0.6 0.6];",
                "    EEG.reject.rejthreshcol = [1 0.6 0.6];",
                "    EEG.reject.rejconstcol = [1 0.6 0.6];",
                "    EEG.reject.rejjpcol = [1 0.6 0.6];",
                "    EEG.reject.rejkurtcol = [1 0.6 0.6];",
                "    EEG.reject.rejfreqcol = [1 0.6 0.6];",
                "end",
                "end",
                "",
                "function capture_simple_pop_dialog(output_file, target_title, action)",
                "fig = findall(0, 'Type', 'figure', 'Name', target_title);",
                "if isempty(fig)",
                "    figs = findall(0, 'Type', 'figure');",
                "    for idx = 1:length(figs)",
                "        fig_name = get(figs(idx), 'Name');",
                "        if contains(fig_name, target_title) || contains(fig_name, action)",
                "            fig = figs(idx);",
                "            break;",
                "        end",
                "    end",
                "end",
                "if isempty(fig), return; end",
                "fig = fig(1);",
                "set(fig, 'Units', 'pixels');",
                "drawnow;",
                "pause(0.2);",
                "write_figure_capture(fig, output_file);",
                "if strcmp(action, 'pop_comments')",
                "    edit_box = findobj(fig, 'tag', 'edit');",
                "    if ~isempty(edit_box)",
                "        set(fig, 'userdata', get(edit_box(1), 'string'));",
                "    else",
                "        set(fig, 'userdata', 'captured');",
                "    end",
                "end",
                "ok_button = findobj('parent', fig, 'tag', 'ok');",
                "if isempty(ok_button), ok_button = findobj(fig, 'tag', 'ok'); end",
                "if isempty(ok_button), ok_button = findall(fig, 'Style', 'pushbutton', 'String', 'Ok'); end",
                "if ~isempty(ok_button)",
                "    set(ok_button(1), 'userdata', 'retuninginputui');",
                "end",
                "try, close(fig); catch, end",
                "end",
                "",
                "function close_headplot_warning()",
                "fig = findall(0, 'Type', 'figure', 'Name', 'Headplot() warning');",
                "if ~isempty(fig), try, close(fig(1)); catch, end, end",
                "end",
                "",
                "function patch_coregister_for_capture(eeglab_root)",
                "source_file = fullfile(eeglab_root, 'functions', 'sigprocfunc', 'coregister.m');",
                "patched_dir = tempname;",
                "mkdir(patched_dir);",
                "source_text = fileread(source_file);",
                "capture_code = [",
                "    'drawnow; pause(0.5); ' ...",
                "    'try, frame = getframe(fid); imwrite(frame.cdata, getenv(''EEGPREP_VISUAL_OUTPUT_FILE'')); catch capture_error, warning(''EEGPrepVisualParity:CoregisterCapture'', ''coregister capture failed: %s'', capture_error.message); end; ' ...",
                "    'set(findobj(''parent'', fid, ''tag'', ''ok''), ''userdata'', ''ok'');'",
                "];",
                "patched_text = strrep(source_text, 'waitfor( findobj(''parent'', fid, ''tag'', ''ok''), ''userdata'');', capture_code);",
                "fid = fopen(fullfile(patched_dir, 'coregister.m'), 'w');",
                "if fid == -1, error('Could not write patched coregister capture file'); end",
                "fwrite(fid, patched_text);",
                "fclose(fid);",
                "addpath(patched_dir, '-begin');",
                "end",
                "",
                "function capture_dipfit_nonlinear_reference(output_file)",
                "try, icadefs; catch, BACKCOLOR = [.66 .76 1]; end",
                "geomvert  = [1 1 1 1 1 1 1 1 1 1 1];",
                "geomhoriz = {",
                "    [0.8 0.5 0.8 1 1]",
                "    [1]",
                "    [0.7 0.7 2 2 1]",
                "    [0.7 0.5 0.2 2 2 1]",
                "    [0.7 0.5 0.2 2 2 1]",
                "    [1]",
                "    [1 1 1]",
                "    [1]",
                "    [1 1 1]",
                "};",
                "geomhoriz = {geomhoriz{:} [1] [1 1 1]};",
                "elements = {};",
                "elements{end+1} = { 'style' 'text'       'string' 'Component to fit' };",
                "elements{end+1} = { 'style' 'edit'       'string' '1' };",
                "elements{end+1} = { 'style' 'pushbutton' 'string' 'Plot map' };",
                "elements{end+1} = { 'style' 'text'       'string' 'Residual variance = ' };",
                "elements{end+1} = { 'style' 'text'       'string' 'not fit' };",
                "elements{end+1} = { };",
                "elements{end+1} = { 'style' 'text'       'string' 'dipole' };",
                "elements{end+1} = { 'style' 'text'       'string' 'fit' };",
                "elements{end+1} = { 'style' 'text'       'string' 'position' };",
                "elements{end+1} = { 'style' 'text'       'string' 'moment' };",
                "elements{end+1} = { };",
                "elements{end+1} = { 'style' 'text'       'string' '1' };",
                "elements{end+1} = { 'style' 'checkbox'   'string' '' 'value' 1 };",
                "elements{end+1} = { };",
                "elements{end+1} = { 'style' 'edit'       'string' '0 0 0' };",
                "elements{end+1} = { 'style' 'edit'       'string' '0 0 0' };",
                "elements{end+1} = { 'style' 'pushbutton' 'string' 'Flip (in|out)' };",
                "elements{end+1} = { 'style' 'text'       'string' '#2' };",
                "elements{end+1} = { 'style' 'checkbox'   'string' '' };",
                "elements{end+1} = { };",
                "elements{end+1} = { 'style' 'edit'       'string' '0 0 0' };",
                "elements{end+1} = { 'style' 'edit'       'string' '0 0 0' };",
                "elements{end+1} = { 'style' 'pushbutton' 'string' 'Flip (in|out)' };",
                "elements{end+1} = { };",
                "elements{end+1} = { 'style' 'checkbox'   'string' 'Symmetry constrain for dipole #2' 'value' 1 };",
                "elements{end+1} = { }; elements{end+1} = { }; elements{end+1} = { };",
                "elements{end+1} = { 'style' 'pushbutton' 'string' 'Fit dipole(s)'' position & moment' };",
                "elements{end+1} = { 'style' 'pushbutton' 'string' 'OR fit only dipole(s)'' moment' };",
                "elements{end+1} = { 'style' 'pushbutton' 'string' 'Plot dipole(s)' };",
                "elements{end+1} = { };",
                "elements{end+1} = { 'Style' 'pushbutton' 'string' 'Cancel' };",
                "elements{end+1} = { 'Style' 'pushbutton' 'string' 'Help' };",
                "elements{end+1} = { 'Style' 'pushbutton' 'string' 'OK' };",
                "fig = figure('visible', 'on', 'color', BACKCOLOR);",
                "supergui(fig, geomhoriz, geomvert, elements{:});",
                "set(fig, 'name', 'Manual dipole fit -- pop_dipfit_nonlinear()', 'Units', 'pixels');",
                "drawnow; pause(0.2);",
                "write_figure_capture(fig, output_file);",
                "try, close(fig); catch, end",
                "end",
                "",
                *_matlab_capture_helper(),
                "",
            ]
        )
    )
    return script_path


def _write_matlab_pop_comments_dialog_script(case: VisualCase, output_path: pathlib.Path) -> pathlib.Path:
    eeglab_root = _eeglab_reference_root()
    script_path = output_path.parent / f"{case.id}_eeglab_capture.m"
    script_path.write_text(
        "\n".join(
            [
                "function eegprep_visual_capture()",
                "try",
                f"output_file = {_matlab_string(output_path)};",
                f"eeglab_root = {_matlab_string(eeglab_root)};",
                "addpath(genpath(eeglab_root));",
                "try, icadefs; catch, BACKCOLOR = [.8 .8 .8]; GUIBUTTONCOLOR = [.8 .8 .8]; end",
                "fig = figure('menubar', 'none', 'tag', 'comment', 'color', BACKCOLOR, 'userdata', 0, ...",
                "    'numbertitle', 'off', 'name', 'Read/Enter text -- pop_comments()');",
                "pos = get(gca, 'position');",
                "q = [pos(1) pos(2) 0 0];",
                "s = [pos(3) pos(4) pos(3) pos(4)]./100;",
                "h = title('About this dataset');",
                "set(h, 'fontname', 'Helvetica', 'fontweight', 'bold', 'interpreter', 'none');",
                "axis off;",
                "uicontrol('Parent', fig, 'Units', 'Normalized', 'Position', [0 -5 20 10].*s+q, ...",
                "    'backgroundcolor', GUIBUTTONCOLOR, 'string', 'CANCEL');",
                "uicontrol('Parent', fig, 'Units', 'Normalized', 'Position', [80 -5 20 10].*s+q, ...",
                "    'backgroundcolor', GUIBUTTONCOLOR, 'string', 'SAVE');",
                "uicontrol('Parent', fig, 'Units', 'Normalized', 'style', 'edit', 'tag', 'edit', ...",
                "    'Position', [0 10 105 85].*s+q, 'string', 'Existing sample dataset comments.', ...",
                "    'backgroundcolor', [1 1 1], 'horizontalalignment', 'left', 'max', 3, 'fontsize', 12);",
                "drawnow;",
                "pause(0.2);",
                "write_figure_capture(fig, output_file);",
                "try, close(fig); catch, end",
                "if exist(output_file, 'file') ~= 2",
                "    error('visual parity capture did not create %s', output_file);",
                "end",
                "exit(0);",
                "catch ME",
                "disp(getReport(ME, 'extended'));",
                "exit(1);",
                "end",
                "end",
                "",
                *_matlab_capture_helper(),
                "eegprep_visual_capture();",
                "",
            ]
        )
    )
    return script_path


def _write_matlab_pop_editeventvals_dialog_script(case: VisualCase, output_path: pathlib.Path) -> pathlib.Path:
    eeglab_root = _eeglab_reference_root()
    script_path = output_path.parent / f"{case.id}_eeglab_capture.m"
    script_path.write_text(
        "\n".join(
            [
                "function eegprep_visual_capture()",
                "try",
                f"output_file = {_matlab_string(output_path)};",
                f"eeglab_root = {_matlab_string(eeglab_root)};",
                "addpath(genpath(eeglab_root));",
                "set(0, 'DefaultFigureVisible', 'on');",
                "EEG = make_eventvals_demo();",
                "allfields = fieldnames(EEG.event);",
                "tmpind = strmatch('urevent', allfields);",
                "allfields(tmpind) = [];",
                "geometry = { [2 0.5] };",
                "tmpstr = sprintf('Edit event field values (currently %d events)', length(EEG.event));",
                "uilist = { { 'Style', 'text', 'string', tmpstr, 'fontweight', 'bold' } ...",
                "           { 'Style', 'pushbutton', 'string', 'Delete event', 'callback', '' } };",
                "for index = 1:length(allfields)",
                "    geometry = { geometry{:} [1 1 1 1] };",
                "    if strcmp(allfields{index}, 'latency') || strcmp(allfields{index}, 'duration')",
                "        if EEG.trials > 1, inputstr = [ allfields{index} ' (ms)' ];",
                "        else, inputstr = [ allfields{index} ' (sec)' ]; end",
                "    else, inputstr = allfields{index}; end",
                "    cbedit = [ 'pop_editeventvals(''assign'', ''' allfields{index} ''');' ];",
                "    uilist = { uilist{:}, { }, ...",
                "        { 'Style', 'pushbutton', 'string', inputstr, 'callback', '' }, ...",
                "        { 'Style', 'edit', 'tag', allfields{index}, 'string', '', 'callback', cbedit }, ...",
                "        { } };",
                "end",
                "geometry = { geometry{:} [1] [1.2 0.6 0.6 1 0.6 0.6 1.2] [1.2 0.6 0.6 1 0.6 0.6 1.2] [2 1 2] };",
                "tpappend = 'Append event after the current event';",
                "tpinsert = 'Insert event before the current event';",
                "tporigin = 'Original index of the event (in EEG.urevent table)';",
                "uilist = { uilist{:}, ...",
                "    { }, ...",
                "    { }, { }, { }, { 'Style', 'text', 'string', 'Event Num', 'fontweight', 'bold' }, { }, { }, { }, ...",
                "    { 'Style', 'pushbutton', 'string', 'Insert event', 'callback', '', 'tooltipstring', tpinsert }, ...",
                "    { 'Style', 'pushbutton', 'string', '<<', 'callback', '' }, ...",
                "    { 'Style', 'pushbutton', 'string', '<', 'callback', '' }, ...",
                "    { 'Style', 'edit', 'string', '1', 'callback', 'pop_editeventvals(''goto'', 0);', 'tag', 'numval' }, ...",
                "    { 'Style', 'pushbutton', 'string', '>', 'callback', '' }, ...",
                "    { 'Style', 'pushbutton', 'string', '>>', 'callback', '' }, ...",
                "    { 'Style', 'pushbutton', 'string', 'Append event', 'callback', '', 'tooltipstring', tpappend }, ...",
                "    { }, { 'Style', 'text', 'string', ' ', 'tag', 'original', 'horizontalalignment', 'center', 'tooltipstring', tporigin }, { } };",
                "userdata = { EEG {} };",
                "inputgui(geometry, uilist, 'pophelp(''pop_editeventvals'');', 'Edit event values -- pop_editeventvals()', userdata, 'plot');",
                "pop_editeventvals('goto', 0);",
                "fig = gcf;",
                "drawnow;",
                "pause(0.2);",
                "write_figure_capture(fig, output_file);",
                "try, close(fig); catch, end",
                "if exist(output_file, 'file') ~= 2",
                "    error('visual parity capture did not create %s', output_file);",
                "end",
                "exit(0);",
                "catch ME",
                "disp(getReport(ME, 'extended'));",
                "exit(1);",
                "end",
                "end",
                "",
                "function EEG = make_eventvals_demo()",
                "EEG = eeg_emptyset;",
                "EEG.setname = 'pop demo';",
                "EEG.nbchan = 4;",
                "EEG.pnts = 1000;",
                "EEG.trials = 1;",
                "EEG.srate = 250;",
                "EEG.xmin = 0;",
                "EEG.xmax = (EEG.pnts-1)/EEG.srate;",
                "EEG.data = zeros(4, EEG.pnts);",
                "EEG.event = struct('type', {'stim', 'resp'}, 'latency', {100, 350}, 'duration', {0, 0}, 'urevent', {1, 2});",
                "EEG.urevent = rmfield(EEG.event, 'urevent');",
                "EEG.eventdescription = {'Event type', 'Latency', 'Duration'};",
                "end",
                "",
                *_matlab_capture_helper(),
                "eegprep_visual_capture();",
                "",
            ]
        )
    )
    return script_path


def _write_matlab_pop_mergeset_dialog_script(case: VisualCase, output_path: pathlib.Path) -> pathlib.Path:
    eeglab_root = _eeglab_reference_root()
    script_path = output_path.parent / f"{case.id}_eeglab_capture.m"
    script_path.write_text(
        "\n".join(
            [
                "function eegprep_visual_capture()",
                "try",
                f"output_file = {_matlab_string(output_path)};",
                f"eeglab_root = {_matlab_string(eeglab_root)};",
                "addpath(genpath(eeglab_root));",
                "set(0, 'DefaultFigureVisible', 'on');",
                "uilist = { { 'style' 'text' 'string' 'Dataset indices to merge' } ...",
                "    { 'style' 'edit' 'string' '1' } ...",
                "    { 'style' 'text' 'string' 'Preserve ICA weights of the first dataset ?' } ...",
                "    { 'style' 'checkbox' 'string' '' } };",
                "inputgui('uilist', uilist, 'geometry', { [3 1] [3 1] }, ...",
                "    'helpcom', 'pophelp(''pop_mergeset'')', 'title', 'Merge datasets -- pop_mergeset()', 'mode', 'plot');",
                "fig = gcf;",
                "drawnow;",
                "pause(0.2);",
                "write_figure_capture(fig, output_file);",
                "try, close(fig); catch, end",
                "if exist(output_file, 'file') ~= 2",
                "    error('visual parity capture did not create %s', output_file);",
                "end",
                "exit(0);",
                "catch ME",
                "disp(getReport(ME, 'extended'));",
                "exit(1);",
                "end",
                "end",
                "",
                *_matlab_capture_helper(),
                "eegprep_visual_capture();",
                "",
            ]
        )
    )
    return script_path


def _write_matlab_dataset_index_dialog_script(case: VisualCase, output_path: pathlib.Path) -> pathlib.Path:
    eeglab_root = _eeglab_reference_root()
    script_path = output_path.parent / f"{case.id}_eeglab_capture.m"
    script_path.write_text(
        "\n".join(
            [
                "function eegprep_visual_capture()",
                "capture_timer = [];",
                "try",
                f"output_file = {_matlab_string(output_path)};",
                f"eeglab_root = {_matlab_string(eeglab_root)};",
                "addpath(genpath(eeglab_root));",
                "set(0, 'DefaultFigureVisible', 'on');",
                "capture_timer = timer( ...",
                "    'ExecutionMode', 'fixedSpacing', ...",
                "    'Period', 0.5, ...",
                "    'StartDelay', 1.0, ...",
                "    'UserData', output_file, ...",
                "    'TimerFcn', @capture_dataset_index_dialog);",
                "start(capture_timer);",
                "answer = inputdlg2({ 'Dataset index' }, 'Choose dataset', 1, { '' });",
                "if exist(output_file, 'file') ~= 2",
                "    error('visual parity capture did not create %s', output_file);",
                "end",
                "try, stop(capture_timer); delete(capture_timer); catch, end",
                "exit(0);",
                "catch ME",
                "try, if ~isempty(capture_timer), stop(capture_timer); delete(capture_timer); end, catch, end",
                "disp(getReport(ME, 'extended'));",
                "exit(1);",
                "end",
                "end",
                "",
                "function capture_dataset_index_dialog(timer_obj, ~)",
                "output_file = get(timer_obj, 'UserData');",
                "figs = findall(0, 'Type', 'figure');",
                "fig = [];",
                "for idx = 1:length(figs)",
                "    fig_name = get(figs(idx), 'Name');",
                "    if contains(fig_name, 'Choose dataset')",
                "        fig = figs(idx);",
                "        break;",
                "    end",
                "end",
                "if isempty(fig), return; end",
                "ok_button = findobj('parent', fig, 'tag', 'ok');",
                "if isempty(ok_button), return; end",
                "set(fig, 'Units', 'pixels');",
                "drawnow;",
                "pause(0.2);",
                "write_figure_capture(fig, output_file);",
                "set(ok_button, 'userdata', 'retuninginputui');",
                "stop(timer_obj);",
                "delete(timer_obj);",
                "end",
                "",
                *_matlab_capture_helper(),
                "eegprep_visual_capture();",
                "",
            ]
        )
    )
    return script_path


def _write_matlab_pophelp_dialog_script(
    case: VisualCase,
    output_path: pathlib.Path,
    function_name: str,
) -> pathlib.Path:
    eeglab_root = _eeglab_reference_root()
    script_path = output_path.parent / f"{case.id}_eeglab_capture.m"
    script_path.write_text(
        "\n".join(
            [
                "function eegprep_visual_capture()",
                "capture_timer = [];",
                "try",
                f"output_file = {_matlab_string(output_path)};",
                f"function_name = {_matlab_string(function_name)};",
                f"eeglab_root = {_matlab_string(eeglab_root)};",
                "addpath(genpath(eeglab_root));",
                "set(0, 'DefaultFigureVisible', 'on');",
                "capture_timer = timer( ...",
                "    'ExecutionMode', 'fixedSpacing', ...",
                "    'Period', 0.5, ...",
                "    'StartDelay', 1.0, ...",
                "    'UserData', struct('output_file', output_file, 'function_name', function_name), ...",
                "    'TimerFcn', @capture_pophelp_dialog);",
                "start(capture_timer);",
                "pophelp(function_name);",
                "pause(2);",
                "if exist(output_file, 'file') ~= 2",
                "    error('visual parity capture did not create %s', output_file);",
                "end",
                "try, stop(capture_timer); delete(capture_timer); catch, end",
                "exit(0);",
                "catch ME",
                "try, if ~isempty(capture_timer), stop(capture_timer); delete(capture_timer); end, catch, end",
                "disp(getReport(ME, 'extended'));",
                "exit(1);",
                "end",
                "end",
                "",
                "function capture_pophelp_dialog(timer_obj, ~)",
                "payload = get(timer_obj, 'UserData');",
                "output_file = payload.output_file;",
                "function_name = payload.function_name;",
                "figs = findall(0, 'Type', 'figure');",
                "fig = [];",
                "for idx = 1:length(figs)",
                "    fig_name = get(figs(idx), 'Name');",
                "    if contains(lower(fig_name), lower(function_name)) || contains(lower(fig_name), 'function help')",
                "        fig = figs(idx);",
                "        break;",
                "    end",
                "end",
                "if isempty(fig)",
                "    if write_java_window_capture(function_name, output_file)",
                "        stop(timer_obj);",
                "        delete(timer_obj);",
                "        return;",
                "    end",
                "    write_pophelp_text_capture(function_name, output_file);",
                "    if exist(output_file, 'file') == 2",
                "        stop(timer_obj);",
                "        delete(timer_obj);",
                "    end",
                "    return;",
                "end",
                "set(fig, 'Units', 'pixels', 'Position', [100 100 720 520]);",
                "drawnow;",
                "pause(0.5);",
                "write_figure_capture(fig, output_file);",
                "try, close(fig); catch, end",
                "stop(timer_obj);",
                "delete(timer_obj);",
                "end",
                "",
                "function captured = write_java_window_capture(function_name, output_file)",
                "captured = false;",
                "try",
                "    frames = java.awt.Frame.getFrames();",
                "    fallback = [];",
                "    for idx = 1:length(frames)",
                "        frame = frames(idx);",
                "        if ~frame.isShowing(), continue; end",
                "        bounds = frame.getBounds();",
                "        if bounds.getWidth() < 300 || bounds.getHeight() < 200, continue; end",
                "        title = char(frame.getTitle());",
                "        if isempty(fallback), fallback = frame; end",
                "        if contains(lower(title), lower(function_name)) || contains(lower(title), 'help') || contains(lower(title), 'web')",
                "            fallback = frame;",
                "            break;",
                "        end",
                "    end",
                "    if isempty(fallback), return; end",
                "    bounds = fallback.getBounds();",
                "    rect = java.awt.Rectangle(bounds.getX(), bounds.getY(), bounds.getWidth(), bounds.getHeight());",
                "    robot = java.awt.Robot;",
                "    img = robot.createScreenCapture(rect);",
                "    javax.imageio.ImageIO.write(img, 'png', java.io.File(output_file));",
                "    captured = true;",
                "catch",
                "    captured = false;",
                "end",
                "end",
                "",
                "function write_pophelp_text_capture(function_name, output_file)",
                "source_path = which(function_name);",
                "help_text = help(function_name);",
                "if length(function_name) > 4 && strcmpi(function_name(1:4), 'pop_')",
                "    called_name = function_name(5:end);",
                "    try",
                "        called_text = help(called_name);",
                "        if ~isempty(called_text)",
                "            divider = sprintf(['\\n___________________________________________________________________\\n\\n' ...",
                "                ' The ''pop'' function above calls the eponymous Matlab function below\\n' ...",
                "                ' and could use some of its optional parameters\\n' ...",
                "                '___________________________________________________________________\\n\\n']);",
                "            help_text = [help_text divider called_text];",
                "        end",
                "    catch",
                "    end",
                "end",
                "fig = figure('Name', [function_name ' - ' upper(function_name)], ...",
                "    'Units', 'pixels', 'Position', [100 100 720 520], ...",
                "    'MenuBar', 'none', 'ToolBar', 'none', 'Color', [1 1 1], ...",
                "    'NumberTitle', 'off');",
                "title_text = sprintf('%s\\n%s\\n\\n%s', upper(function_name), source_path, help_text);",
                "uicontrol('Parent', fig, 'Style', 'edit', 'String', title_text, ...",
                "    'Units', 'pixels', 'Position', [16 16 688 488], ...",
                "    'HorizontalAlignment', 'left', 'Max', 2, 'Min', 0, ...",
                "    'BackgroundColor', [1 1 1], 'ForegroundColor', [0 0 0], ...",
                "    'FontName', 'Monospaced', 'FontSize', 10);",
                "drawnow;",
                "pause(0.2);",
                "write_figure_capture(fig, output_file);",
                "try, close(fig); catch, end",
                "end",
                "",
                *_matlab_capture_helper(),
                "eegprep_visual_capture();",
                "",
            ]
        )
    )
    return script_path


def _write_matlab_pop_chansel_dialog_script(case: VisualCase, output_path: pathlib.Path) -> pathlib.Path:
    eeglab_root = _eeglab_reference_root()
    script_path = output_path.parent / f"{case.id}_eeglab_capture.m"
    call = "[chanlist, chanliststr, allchanstr] = pop_chansel({'Fp1', 'Fp2', 'Cz', 'Oz'}, 'withindex', 'on');"
    script_path.write_text(
        "\n".join(
            [
                "function eegprep_visual_capture()",
                "capture_timer = [];",
                "try",
                f"output_file = {_matlab_string(output_path)};",
                f"eeglab_root = {_matlab_string(eeglab_root)};",
                "addpath(genpath(eeglab_root));",
                "set(0, 'DefaultFigureVisible', 'on');",
                "capture_timer = timer( ...",
                "    'ExecutionMode', 'fixedSpacing', ...",
                "    'Period', 0.5, ...",
                "    'StartDelay', 0.5, ...",
                "    'UserData', output_file, ...",
                "    'TimerFcn', @capture_pop_chansel_dialog);",
                "start(capture_timer);",
                call,
                "if exist(output_file, 'file') ~= 2",
                "    error('visual parity capture did not create %s', output_file);",
                "end",
                "try, stop(capture_timer); delete(capture_timer); catch, end",
                "exit(0);",
                "catch ME",
                "try, if ~isempty(capture_timer), stop(capture_timer); delete(capture_timer); end, catch, end",
                "disp(getReport(ME, 'extended'));",
                "exit(1);",
                "end",
                "end",
                "",
                "function capture_pop_chansel_dialog(timer_obj, ~)",
                "output_file = get(timer_obj, 'UserData');",
                "listbox = findobj(0, 'tag', 'listboxvals');",
                "if isempty(listbox), return; end",
                "fig = ancestor(listbox(1), 'figure');",
                "if isempty(fig), return; end",
                "set(fig, 'Units', 'pixels');",
                "drawnow;",
                "pause(0.2);",
                "write_figure_capture(fig, output_file);",
                "set(fig, 'userdata', 'cancel');",
                "drawnow;",
                "pause(0.1);",
                "try, close(fig); catch, end",
                "stop(timer_obj);",
                "delete(timer_obj);",
                "end",
                "",
                *_matlab_capture_helper(),
                "eegprep_visual_capture();",
                "",
            ]
        )
    )
    return script_path


def _write_matlab_select_multiple_datasets_dialog_script(case: VisualCase, output_path: pathlib.Path) -> pathlib.Path:
    eeglab_root = _eeglab_reference_root()
    script_path = output_path.parent / f"{case.id}_eeglab_capture.m"
    script_path.write_text(
        "\n".join(
            [
                "function eegprep_visual_capture()",
                "try",
                f"output_file = {_matlab_string(output_path)};",
                f"eeglab_root = {_matlab_string(eeglab_root)};",
                "addpath(genpath(eeglab_root));",
                "try, icadefs; catch, BACKCOLOR = [.66 .76 1]; GUIBUTTONCOLOR = [.8 .8 .8]; end",
                "fig = figure('menubar', 'none', 'numbertitle', 'off', 'name', '', ...",
                "    'Units', 'pixels', 'Position', [100 100 300 195], 'Color', BACKCOLOR);",
                "uicontrol('Parent', fig, 'Style', 'text', 'String', sprintf('(use shift|Ctrl to\\nselect several)'), ...",
                "    'Units', 'pixels', 'Position', [18 135 264 40], 'HorizontalAlignment', 'left', ...",
                "    'BackgroundColor', BACKCOLOR, 'ForegroundColor', [0 0 .4]);",
                "uicontrol('Parent', fig, 'Style', 'listbox', 'Tag', 'listboxvals', ...",
                "    'String', {'1  -  Dataset 1:menu one', '2  -  Dataset 2:menu two', '3  -  Dataset 3:menu three'}, ...",
                "    'Value', [1 2], 'Min', 0, 'Max', 2, 'Units', 'pixels', 'Position', [18 45 264 88], ...",
                "    'BackgroundColor', [1 1 1], 'ForegroundColor', [0 0 0]);",
                "uicontrol('Parent', fig, 'Style', 'pushbutton', 'String', 'Cancel', ...",
                "    'Units', 'pixels', 'Position', [18 12 62 18], 'BackgroundColor', GUIBUTTONCOLOR);",
                "uicontrol('Parent', fig, 'Style', 'pushbutton', 'String', 'Ok', ...",
                "    'Units', 'pixels', 'Position', [220 12 62 18], 'BackgroundColor', GUIBUTTONCOLOR);",
                "drawnow;",
                "pause(0.2);",
                "write_figure_capture(fig, output_file);",
                "try, close(fig); catch, end",
                "if exist(output_file, 'file') ~= 2",
                "    error('visual parity capture did not create %s', output_file);",
                "end",
                "exit(0);",
                "catch ME",
                "disp(getReport(ME, 'extended'));",
                "exit(1);",
                "end",
                "end",
                "",
                *_matlab_capture_helper(),
                "eegprep_visual_capture();",
                "",
            ]
        )
    )
    return script_path


def _run_subprocess(
    target_name: str,
    output_path: pathlib.Path,
    command: list[str],
    env: dict[str, str],
    timeout_seconds: int,
) -> CaptureResult:
    try:
        completed = subprocess.run(
            command,
            cwd=REPO_ROOT,
            env=env,
            text=True,
            capture_output=True,
            timeout=timeout_seconds,
            check=False,
        )
    except FileNotFoundError as exc:
        return CaptureResult(target_name, output_path, command, 127, stderr=str(exc))
    except subprocess.TimeoutExpired as exc:
        return CaptureResult(
            target_name,
            output_path,
            command,
            124,
            stdout=exc.stdout or "",
            stderr=f"capture timed out after {timeout_seconds} seconds",
        )
    return CaptureResult(
        target=target_name,
        output_path=output_path,
        command=command,
        exit_code=completed.returncode,
        stdout=completed.stdout,
        stderr=completed.stderr,
    )


def capture_target(
    case: VisualCase,
    target_name: str,
    output_dir: pathlib.Path = DEFAULT_OUTPUT_DIR,
    command_override: str | None = None,
    matlab_executable: str = "matlab",
    timeout_seconds: int | None = None,
) -> CaptureResult:
    """Capture one target for a visual parity case."""
    if target_name not in case.targets:
        raise ValueError(f"{case.id}: no {target_name} target is configured")

    target = case.targets[target_name]
    output_path = _output_path(output_dir, case.id, target_name)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    timeout = timeout_seconds or case.timeout_seconds
    env = _target_env(case, target_name, target, output_path)
    values = _command_values(case, target_name, output_path)
    values["action"] = target.action

    if command_override:
        command = [part.format(**values) for part in shlex.split(command_override)]
    elif target.type == "matlab_figure" and target_name == "eeglab":
        if shutil.which(matlab_executable) is None:
            return CaptureResult(
                target_name,
                output_path,
                [matlab_executable, "-nosplash", "-nodesktop", "-r", "<generated capture script>"],
                127,
                stderr=f"MATLAB executable not found: {matlab_executable}",
            )
        script_path = _write_matlab_figure_script(case, target, output_path)
        command = [matlab_executable, "-nosplash", "-nodesktop", "-r", _matlab_run_expression(script_path)]
    elif target.type == "matlab_dialog" and target_name == "eeglab":
        action, variant = _split_action(target.action)
        if action not in {
            "pop_adjustevents",
            "pop_chanedit",
            "pop_chansel",
            "pop_clean_rawdata",
            "pop_comments",
            "pop_copyset",
            "pop_editset",
            "pop_eegfilt",
            "pop_eegfiltnew",
            "pop_editeventfield",
            "pop_editeventvals",
            "pop_epoch",
            "pop_firma",
            "pop_firpm",
            "pop_firws",
            "pop_icflag",
            "pop_iclabel",
            "pop_interp",
            "pop_mergeset",
            "pop_study",
            "pop_studydesign",
            "pop_resample",
            "pop_rmdat",
            "pop_reref",
            "pop_rmbase",
            "pop_runica",
            "pop_select",
            "pop_selectevent",
            "pop_spectopo",
            "pop_subcomp",
            "pop_prop",
            "pop_timtopo",
            "pop_plottopo",
            "pop_headplot",
            "pop_plotdata",
            "pop_erpimage",
            "pop_envtopo",
            "pop_comperp",
            "pop_newtimef",
            "pop_newcrossf",
            "pop_signalstat",
            "pop_eventstat",
            "pop_topoplot",
            "coregister",
            "select_multiple_datasets",
            "pop_autorej",
            "pop_eegthresh",
            "pop_jointprob",
            "pop_rejchan",
            "pop_rejcont",
            "pop_rejkurt",
            "pop_rejmenu",
            "pop_rejspec",
            "pop_rejtrend",
            "pop_selectcomps",
            "pop_viewprops",
            "pop_dipfit_settings",
            "pop_dipfit_headmodel",
            "pop_dipfit_gridsearch",
            "pop_dipfit_nonlinear",
            "pop_dipplot",
            "pop_multifit",
            "pop_leadfield",
            "pop_dipfit_loreta",
            "inputdlg2",
            "pophelp",
        }:
            return CaptureResult(
                target_name,
                output_path,
                [],
                2,
                stderr=f"unsupported MATLAB dialog action: {target.action}",
            )
        if shutil.which(matlab_executable) is None:
            return CaptureResult(
                target_name,
                output_path,
                [matlab_executable, "-nosplash", "-nodesktop", "-r", "<generated dialog capture script>"],
                127,
                stderr=f"MATLAB executable not found: {matlab_executable}",
            )
        if action in {"pop_adjustevents", "pop_interp"}:
            script_path = _write_matlab_simple_pop_dialog_script(case, output_path, action, variant)
        elif action == "pop_comments":
            script_path = _write_matlab_pop_comments_dialog_script(case, output_path)
        elif action == "pop_editeventvals":
            script_path = _write_matlab_pop_editeventvals_dialog_script(case, output_path)
        elif action == "pop_mergeset":
            script_path = _write_matlab_pop_mergeset_dialog_script(case, output_path)
        elif action == "pop_chansel":
            script_path = _write_matlab_pop_chansel_dialog_script(case, output_path)
        elif action == "select_multiple_datasets":
            script_path = _write_matlab_select_multiple_datasets_dialog_script(case, output_path)
        elif action in {
            "pop_chanedit",
            "pop_clean_rawdata",
            "pop_copyset",
            "pop_editset",
            "pop_eegfilt",
            "pop_eegfiltnew",
            "pop_editeventfield",
            "pop_epoch",
            "pop_firma",
            "pop_firpm",
            "pop_firws",
            "pop_icflag",
            "pop_iclabel",
            "pop_study",
            "pop_studydesign",
            "pop_resample",
            "pop_rmdat",
            "pop_rmbase",
            "pop_runica",
            "pop_select",
            "pop_selectevent",
            "pop_spectopo",
            "pop_subcomp",
            "pop_prop",
            "pop_timtopo",
            "pop_plottopo",
            "pop_headplot",
            "pop_plotdata",
            "pop_erpimage",
            "pop_envtopo",
            "pop_comperp",
            "pop_newtimef",
            "pop_newcrossf",
            "pop_signalstat",
            "pop_eventstat",
            "pop_topoplot",
            "coregister",
            "pop_autorej",
            "pop_eegthresh",
            "pop_jointprob",
            "pop_rejchan",
            "pop_rejcont",
            "pop_rejkurt",
            "pop_rejmenu",
            "pop_rejspec",
            "pop_rejtrend",
            "pop_selectcomps",
            "pop_viewprops",
            "pop_dipfit_settings",
            "pop_dipfit_headmodel",
            "pop_dipfit_gridsearch",
            "pop_dipfit_nonlinear",
            "pop_dipplot",
            "pop_multifit",
            "pop_leadfield",
            "pop_dipfit_loreta",
        }:
            script_path = _write_matlab_simple_pop_dialog_script(case, output_path, action, variant)
        elif action == "inputdlg2":
            script_path = _write_matlab_dataset_index_dialog_script(case, output_path)
        elif action == "pophelp":
            script_path = _write_matlab_pophelp_dialog_script(case, output_path, variant)
        else:
            script_path = _write_matlab_reref_dialog_script(case, output_path, variant)
        command = [matlab_executable, "-nosplash", "-nodesktop", "-r", _matlab_run_expression(script_path)]
    else:
        if not target.command:
            message = (
                f"{case.id}/{target_name} has no capture command. Add one to "
                f"{DEFAULT_MANIFEST} or pass --{target_name}-command."
            )
            return CaptureResult(target_name, output_path, [], 2, stderr=message)
        command = format_command(target.command, values)

    return _run_subprocess(target_name, output_path, command, env, timeout)


def capture_case(
    case: VisualCase,
    target: str,
    output_dir: pathlib.Path = DEFAULT_OUTPUT_DIR,
    eeglab_command: str | None = None,
    eegprep_command: str | None = None,
    matlab_executable: str = "matlab",
    timeout_seconds: int | None = None,
) -> list[CaptureResult]:
    """Capture one or both targets for a case."""
    target_names = ["eeglab", "eegprep"] if target == "both" else [target]
    overrides = {"eeglab": eeglab_command, "eegprep": eegprep_command}
    return [
        capture_target(
            case,
            target_name,
            output_dir=output_dir,
            command_override=overrides[target_name],
            matlab_executable=matlab_executable,
            timeout_seconds=timeout_seconds,
        )
        for target_name in target_names
    ]


def _print_result(result: CaptureResult) -> None:
    status = "ok" if result.ok else "FAIL"
    print(f"{result.target}: {status} -> {result.output_path}")
    if result.command:
        print("  command:", shlex.join(result.command))
    if result.stdout.strip():
        print("  stdout:")
        print(result.stdout.rstrip())
    if result.stderr.strip():
        print("  stderr:")
        print(result.stderr.rstrip())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=pathlib.Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output-dir", type=pathlib.Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--case", help="Visual parity case id")
    parser.add_argument("--target", choices=["eeglab", "eegprep", "both"], default="both")
    parser.add_argument("--list", action="store_true", help="List configured cases")
    parser.add_argument("--eeglab-command", help="Override command for the EEGLAB target")
    parser.add_argument("--eegprep-command", help="Override command for the EEGPrep target")
    parser.add_argument("--matlab-executable", default="matlab")
    parser.add_argument("--timeout", type=int, help="Override capture timeout in seconds")
    args = parser.parse_args(argv)

    cases = load_manifest(args.manifest)
    if args.list:
        for case in cases.values():
            print(f"{case.id}: {case.description}")
        return 0

    if not args.case:
        parser.error("--case is required unless --list is used")
    if args.case not in cases:
        parser.error(f"unknown case: {args.case}")

    results = capture_case(
        cases[args.case],
        args.target,
        output_dir=args.output_dir,
        eeglab_command=args.eeglab_command,
        eegprep_command=args.eegprep_command,
        matlab_executable=args.matlab_executable,
        timeout_seconds=args.timeout,
    )
    for result in results:
        _print_result(result)
    return 0 if all(result.ok for result in results) else 1


if __name__ == "__main__":
    sys.exit(main())
